Repository projectceladon/vendor-intel-utils, pull requests merged in 2022-07, with the labels that each got.

#1486 Integrate JULY-2022 ASB patches to CELADON Master
  aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/av/11_0011-C2Allocator-protetct-memory-mappings-from-race-condi.patch
  aosp_diff/preliminary/frameworks/base/38_0038-StorageManagerService-don-t-ignore-failures-to-prepare-user.patch
  aosp_diff/preliminary/frameworks/base/39_0039-UserDataPreparer-reboot-to-recovery-if-preparing-user-stora.patch
  aosp_diff/preliminary/frameworks/base/40_0040-UserDataPreparer-reboot-to-recovery-for-system-user-only.patch
  aosp_diff/preliminary/frameworks/base/41_0041-Ignore-errors-preparing-user-storage-for-existing-users.patch
  aosp_diff/preliminary/frameworks/base/42_0042-Log-to-EventLog-on-prepareUserStorage-failure.patch
  aosp_diff/preliminary/frameworks/base/43_0043-USB-Increase-debounce-time-for-DISCONNECT-processing-revis.patch
  aosp_diff/preliminary/frameworks/base/44_0044-Add-excludedPackages-parameter-to-broadcast.patch
  aosp_diff/preliminary/frameworks/base/45_0045-Update-ServiceState-broadcast-for-location-permissions.patch
  aosp_diff/preliminary/frameworks/base/46_0046-DO-NOT-MERGE-WM-Call-Transaction-sanitize.patch
  aosp_diff/preliminary/frameworks/native/04_0004-DO-NOT-MERGE-SurfaceFlinger-Add-Transaction-sanitize.patch
  aosp_diff/preliminary/frameworks/opt/telephony/01_0001-Enforce-privileged-phone-state-for-getSubscriptionProperty-G.patch
  aosp_diff/preliminary/packages/apps/KeyChain/01_0001-Encode-authority-part-of-uri-before-showing-in-UI.patch
  aosp_diff/preliminary/packages/apps/Settings/12_0012-Fix-LaunchAnyWhere-in-AppRestrictionsFragment.patch
  aosp_diff/preliminary/packages/modules/Permission/01_0001-Default-overrideUserWhenGranting-to-false.patch
  aosp_diff/preliminary/packages/modules/Permission/02_0002-Allow-bypassing-qualification-for-system-speech-reco.patch
  aosp_diff/preliminary/packages/modules/Permission/03_0003-Fix-incorrect-auto-grant-for-split-permissions.patch
  aosp_diff/preliminary/packages/providers/ContactsProvider/01_0001-DO-NOT-MERGE-Add-check-that-prevents-file-operations-outside.patch
  aosp_diff/preliminary/system/bt/02_0002-Security-Fix-out-of-bound-write-in-HFP-client.patch
  aosp_diff/preliminary/system/bt/03_0003-Check-Avrcp-packet-vendor-length-before-extracting-length.patch
  aosp_diff/preliminary/system/bt/04_0004-Security-Fix-out-of-bound-read-in-AT_SKIP_REST.patch
  aosp_diff/preliminary/system/bt/10_0010-Fix-out-of-bond-write-in-gatt_db.patch
Labels: Valid commit message

#1491 [CiV] SRIOV power management POWER event
  bsp_diff/common/kernel/lts2020-yocto/24_0024-ACPI-PM-Propagate-power-button-event-to-user-space-w.patch
  host/qemu/0033-CiV-SRIOV-virtio-gpu-power-management-qemu.patch
Labels: Valid commit message

#1467 drm/i915: enable 8K60
  bsp_diff/common/kernel/lts2020-yocto/25_0025-drm-i915-dp-HACK-remove-TPS4-to-avoid-LT-failure-iss.patch
  bsp_diff/common/kernel/lts2020-yocto/26-0026-drm-i915-gem-Don-t-evict-unmappable-VMAs-when-pinning-with-PIN_MAPPABLE-v2.patch
Labels: Valid commit message

#1496 [CiV] SRIOV power management host suspend and wakeup
  host/kernel/lts2020-yocto/0002-drm-i915-iov-Fix-suspend-hibernate-when-VFs-are-enab.patch
Labels: Valid commit message

#1495 kernel: Update build script with latest commit hash for v5.10.118
  host/kernel/lts2020-chromium/build_weekly.sh
Labels: Valid commit message

#1497 Allow sgdisk and mmd to make USB disk installer image
  aosp_diff/preliminary/build/soong/0010-Allow-sgdisk-and-mmd-to-make-USB-disk-installer-imag.patch
Labels: Valid commit message, PR approved

#1506 Excluding gki-testcases for android_x86/x86_64
  aosp_diff/preliminary/test/vts-testcase/kernel/gki/0001-Excluding-gki-testcases-for-android_x86-x86_64.patch
Labels: Valid commit message, PR approved

#1508 kernel: Update build script with latest commit hash
  host/kernel/lts2020-chromium/build_weekly.sh
Labels: Valid commit message, PR approved

#1518 kernel: Update build script with latest commit hash
  host/kernel/lts2020-chromium/build_weekly.sh
Labels: Valid commit message, PR approved

#1523 kernel: Update build script with latest commit hash
  host/kernel/lts2020-chromium/build_weekly.sh
Labels: Valid commit message, PR approved

#1528 Add required fw support for GfP upto core71
  bsp_diff/common/vendor/linux/firmware/0003-Add-required-fw-support-for-GfP-upto-core71.patch
Labels: Valid commit message, PR approved

#1520 Freeze and Restore Implementation.
  bsp_diff/common/kernel/lts2020-chromium/21_0021-VIRTIO-Freeze-and-Restore-Implementation.patch
Labels: Invalid commit message
