Repository projectceladon/vendor-intel-utils, pull requests merged in 2022-06, with the labels that each got.

#1463 Added github actions for basic checks
  .github/workflows/Runchecks.yaml
Labels: Linting passed, Invalid commit message

#1484 Added PR LABEL in workflow
  .github/workflows/Runchecks.yaml
Labels: Invalid commit message

#1488 [CIV] SRIOV virtio-gpu PM.
  bsp_diff/common/kernel/lts2020-yocto/22_0022-Operations-on-FB-during-suspend-resume-only-when-dis.patch
  bsp_diff/common/kernel/lts2020-yocto/23_0023-CiV-SRIOV-virtio-gpu-power-management-kernel.patch
  host/qemu/0033-CiV-SRIOV-virtio-gpu-power-management-qemu.patch
Labels: Valid commit message
