Repository projectceladon/vendor-intel-utils, pull requests merged in 2022-10, with the labels that each got.

#1596 Fix volume up/down button issue with 3.5mm
  bsp_diff/common/kernel/lts2020-chromium/43_0043-Fix-volume-up-down-button-issue-with-3.5mm.patch
Labels: Invalid commit message, PR approved

#1624 Fix volume up/down button issue with 3.5mm
  bsp_diff/common/kernel/lts2020-chromium/22_0022-Fix-volume-up-down-button-issue-with-3.5mm.patch
Labels: Invalid commit message, PR approved

#1627 Clean up bsp_diff bluetooth patches
  bsp_diff/common/vendor/intel/hardware/interfaces/0001-Changes-to-avoid-build-issues-in-Android-S.patch
  bsp_diff/common/vendor/intel/hardware/interfaces/02_0002-Update-dependecy-path-for-bt.patch
Labels: PR approved

#1630 remove multi camera diff patches
  bsp_diff/common/vendor/intel/external/apps/camera/0001-clean-multi-camera-application.patch
  bsp_diff/common/vendor/intel/external/apps/camera/0002-convert-android-mk-android-bp.patch
  bsp_diff/common/vendor/intel/external/apps/camera/0003-correct-multi-camera-name.patch
Labels: Invalid commit message, PR approved

#1633 CVE: Update build script with latest commit hash for v5.10.118
  host/kernel/lts2020-chromium/build_weekly.sh
Labels: PR approved

#1635 Rename license file placed in utils so that to
  license-file-for-tarball
Labels: Valid commit message, PR approved

#1615 ART-Runtime Patches
  aosp_diff/preliminary/art/0001-Modify-install-hook-check-in-art.patch
  aosp_diff/preliminary/art/0002-Auto-Fast-JNI-Optimization.patch
Labels: Invalid commit message, PR approved

#1636 Port required bionic patches to Android-13
  aosp_diff/preliminary/bionic/0001-Optimize-bionic-memory-functions-with-avx2-instructi.patch
  aosp_diff/preliminary/bionic/0002-Optimize-bionic-string-functions-with-avx-implementa.patch
  aosp_diff/preliminary/bionic/0003-Linker-changes-to-allow-perf-variants-of-an-.so.patch
Labels: Valid commit message, PR approved

#1632 ASB - Security Patch integration November 2022 - T-MR0-MASTER
  aosp_diff/preliminary/build/make/0004-Update-Security-patch-level.patch
  aosp_diff/preliminary/external/dtc/0002-0001-Fix-integer-wrap-sanitisation-.bulletin.patch
  aosp_diff/preliminary/frameworks/av/0006--Fix-vulnerability-setSecurityLevel-in-clearkey.bulletin.patch
  aosp_diff/preliminary/frameworks/base/10_0010-Stop-crashing-the-system-on-hitting-the-alarm-limit.bulletin.patch
  aosp_diff/preliminary/frameworks/base/11_0011-Revert-Revert-Limit-the-number-of-concurrently-snoozed-not.bulletin.patch
  aosp_diff/preliminary/frameworks/base/12_0012-switch-TelecomManager-List-getters-to-ParceledListSlice.bulletin.patch
  aosp_diff/preliminary/frameworks/base/13_0013-Move-accountname-and-typeName-length-check-from-Account-java.bulletin.patch
  aosp_diff/preliminary/frameworks/base/14-0014-Do-not-send-new-Intent-to-non-exported-activity-when-navigat.bulletin.patch
  aosp_diff/preliminary/frameworks/base/15_0015-Do-not-send-AccessibilityEvent-if-notification-is-for-differ.bulletin.patch
  aosp_diff/preliminary/frameworks/base/16_0016-Update-BaseBundle-to-not-use-LazyValues-when-using-ReadWrite.bulletin.patch
  aosp_diff/preliminary/frameworks/base/17_0017-Check-rule-package-name-in-ZenModeHelper-addAutomaticRule.bulletin.patch
  aosp_diff/preliminary/frameworks/base/18_0018-Fix-auto-grant-of-AR-runtime-permission-if-device-is-upgradi.bulletin.patch
  aosp_diff/preliminary/frameworks/base/19_0019-Trim-any-long-string-inputs-that-come-in-to-AutomaticZenRule.bulletin.patch
  aosp_diff/preliminary/frameworks/base/20_0020-Remove-legacy-WRITE_EXTERNAL_STORAGE-permission-check-for-In.bulletin.patch
  aosp_diff/preliminary/frameworks/base/21_0021-Do-not-dismiss-keyguard-after-SIM-PUK-unlock.bulletin.patch
  aosp_diff/preliminary/frameworks/base/22_0022-Fix-system-zen-rules-by-using-owner-package-name-if-caller-i.bulletin.patch
  aosp_diff/preliminary/hardware/nxp/nfc/0001-OOBW-in-phNxpNciHal_write_unlocked-.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0006-Add-local-to-pan_api-cc.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0007-Add-negative-length-check-in-process_service_search_rsp.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0008-Add-buffer-in-pin_reply-in-bluetooth-cc.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/0002--DO-NOT-MERGE-wifi-remove-certificates-for-network-factory.bulletin.patch
  aosp_diff/preliminary/packages/providers/TelephonyProvider/0001-Check-dir-path-before-updating-permissions-.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/0001-switch-TelecomManager-List-getters-to-ParceledListSlice.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/0002-Fix-security-vulnerability-issue-for-multi-user-call-redirec.bulletin.patch
Labels: Valid commit message, PR approved

#1634 ASB - Security Patch integration November 2022 - smr0_stable
  aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/external/dtc/02_0002-Fix-integer-wrap-sanitisation-.bulletin.patch
  aosp_diff/preliminary/frameworks/av/16_0016--Fix-vulnerability-setSecurityLevel-in-clearkey.bulletin.patch
  aosp_diff/preliminary/frameworks/base/63_0063-Stop-crashing-the-system-on-hitting-the-alarm-limit.bulletin.patch
  aosp_diff/preliminary/frameworks/base/64_0064-DO-NOT-MERGE-Move-accountname-and-typeName-length-check-from.bulletin.patch
  aosp_diff/preliminary/frameworks/base/65_0065-switch-TelecomManager-List-getters-to-ParceledListSlice.bulletin.patch
  aosp_diff/preliminary/frameworks/base/66_0066--RESTRICT-AUTOMERGE-Do-not-send-new-Intent-to-non-exported-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/67_0067-Do-not-send-AccessibilityEvent-if-notification-is-for-differ.bulletin.patch
  aosp_diff/preliminary/frameworks/base/68_0068-DO-NOT-MERGE-Fix-auto-grant-of-AR-runtime-permission-if-devi.bulletin.patch
  aosp_diff/preliminary/frameworks/base/69_0069-Check-rule-package-name-in-ZenModeHelper-addAutomaticRule.bulletin.patch
  aosp_diff/preliminary/frameworks/base/70_0070-Trim-any-long-string-inputs-that-come-in-to-AutomaticZenRule.bulletin.patch
  aosp_diff/preliminary/frameworks/base/71_0071-Fix-system-zen-rules-by-using-owner-package-name-if-caller-i.bulletin.patch
  aosp_diff/preliminary/frameworks/base/72_0072-Make-sure-parallel-broadcasts-enforce-excluded-permissions.bulletin.patch
  aosp_diff/preliminary/frameworks/base/73_0073--DO-NOT-MERGE-Do-not-dismiss-keyguard-after-SIM-PUK-unlock.bulletin.patch
  aosp_diff/preliminary/frameworks/base/74_0074-Limit-the-number-of-concurrently-snoozed-notificatio.patch
  aosp_diff/preliminary/hardware/nxp/nfc/0001-OOBW-in-phNxpNciHal_write_unlocked-.bulletin.patch
  aosp_diff/preliminary/packages/modules/Permission/04_0004-Hide-overlays-on-ReviewPermissionsAtivity.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/0001--DO-NOT-MERGE-wifi-remove-certificates-for-network-factory.bulletin.patch
  aosp_diff/preliminary/packages/providers/TelephonyProvider/0001-Check-dir-path-before-updating-permissions-.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/03_0003-switch-TelecomManager-List-getters-to-ParceledListSlice.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/04_0004-DO-NOT-MERGE-Fix-security-vulnerability-issue-for-multi-user.bulletin.patch
  aosp_diff/preliminary/system/bt/14_0014-Add-negative-length-check-in-process_service_search_rsp.bulletin.patch
  aosp_diff/preliminary/system/bt/15_0015-resolve-merge-conflicts-of-9c93920de7a8d8106a1bc2e11ebfed79d.bulletin.patch
Labels: PR approved
