Repository projectceladon/vendor-intel-utils, pull requests merged in 2022-09, with the labels that each got.

#1570 Integrate SEP-2022 ASB patches to T-MR0-CELADON-MASTER
  aosp_diff/preliminary/build/make/0004-Update-Security-patch-level.patch
  aosp_diff/preliminary/packages/apps/Settings/0001-Make-bluetooth-not-discoverable-via-large-screen-deep-link-f.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/0001-Prevent-restricted-user-from-adding-network-through-camera.bulletin.patch
  aosp_diff/preliminary/packages/providers/MediaProvider/0001-DO-NOT-MERGE-Avoid-path-traversal-in-MediaProvider-delete-ca.bulletin.patch
Labels: Valid commit message

#1585 remove vhal diff patch for ivi
  bsp_diff/celadon_ivi/vendor/intel/external/project-celadon/camera-vhal/0001-civ-changes-on-top-of-vhal-changes.patch
  bsp_diff/celadon_ivi/vendor/intel/external/project-celadon/camera-vhal/0002-VHAL-changes-for-orien-w.r.t-facing.patch
  bsp_diff/celadon_ivi/vendor/intel/external/project-celadon/camera-vhal/0003-Add-check-bit-for-every-frame-recv.patch
  bsp_diff/celadon_ivi/vendor/intel/external/project-celadon/camera-vhal/0004-VTS-fixes-on-VHAL.patch
  bsp_diff/celadon_ivi/vendor/intel/external/project-celadon/camera-vhal/0005-moving-to-new-VHAL-for-multi-resolution.patch
  bsp_diff/celadon_ivi/vendor/intel/external/project-celadon/camera-vhal/0006-mjpeg-support-for-mediation.patch
Labels: Invalid commit message, PR approved

#1564 upgrading sensors@1.0-service to sensors@2.0-service
  bsp_diff/common/kernel/lts2020-chromium/42_0042-VIRTIO-Freeze-and-Restore-Implementation.patch
  bsp_diff/common/vendor/intel/hardware/interfaces/03_0003-REVERT-ME-Revert-Scaling-Magnetometer-raw-values-for-CTS-verif.patch
  bsp_diff/common/vendor/intel/hardware/interfaces/04_0004-REVERT-ME-Revert-Upgrade-sensor-service-from-1.0-to-2.0.patch
  bsp_diff/common/vendor/intel/hardware/interfaces/05_0005-REVERT-ME-Revert-Upgrade-sensor-service-from-1.0-to-2.0.patch
Labels: Valid commit message, PR approved

#1598 kernel: Update build script with latest commit hash for 5.15.44
  host/kernel/lts2021-chromium/build_weekly.sh
Labels: Valid commit message, PR approved

#1600 kernel: Fix patch conflict and build script issues
  host/kernel/lts2021-chromium/0005-Fix-device-hang-on-TGL-RVP.patch
  host/kernel/lts2021-chromium/build_weekly.sh
Labels: Valid commit message

#1601 [bsp_diff:kernel/ACPI]: add bsp diff patch
  bsp_diff/common/kernel/lts2021-chromium/20_0020-ACPI-PM-Propagate-power-button-event-to-user-space-w.patch
Labels: Valid commit message, PR approved

#1595 Remove qemu patch from bsp_diff
  bsp_diff/common/vendor/intel/external/project-celadon/audio/01_679470_1-Tuning-period_size-and-period_count-for-QEMU-KVM.patch
Labels: Valid commit message, PR approved

#1602 upgrading sensors@1.0service to sensors@2.0service
  bsp_diff/common/kernel/lts2021-chromium/20_0020-VIRTIO-Freeze-and-Restore-Implementation.patch
Labels: Valid commit message

#1606 Fix phone process crash when there is no modem
  aosp_diff/preliminary/packages/services/Telephony/01_0001-Fix-phone-process-crash-when-there-is-no-modem.patch
Labels: Valid commit message, PR approved

#1560 Port "Add support for override_lib_name" to Android-13
  aosp_diff/preliminary/build/soong/0007-Add-support-for-overide_lib_name-for-IA-perf-variant.patch
Labels: Valid commit message, PR approved

#1608 kernel: Fix host kernel build issue
  host/kernel/lts2021-chromium/build_weekly.sh
Labels: PR approved

#1610 Update VIRTIO_ID_TRUSTY_IPC from 13 to 14
  bsp_diff/common/kernel/lts2020-yocto/50_0050-Update-VIRTIO_ID_TRUSTY_IPC-from-13-to-14.patch
Labels: Valid commit message, PR approved

#1593 Moving Thermal Diff patch from BSP to AOSP diff
  aosp_diff/preliminary/hardware/interfaces/10_0010-Fix-for-VTS-issue-in-thermal.patch
Labels: Valid commit message, PR approved

#1614 Aosp rebase android-13.0.0_r4 on master branch
  aosp_diff/preliminary/build/make/0004-Update-Security-patch-level.patch
  aosp_diff/preliminary/external/drm_hwcomposer/01_0001-Use-private-drm_hwcomposer-instead-of-external-drm_h.patch
Labels: Valid commit message, PR approved

#1616 Fix drawing delay issue in cases of resize and rotation for SRIOV
  host/qemu/0008-Fix-drawing-delay-issue-in-cases-of-resize-and-rotat.patch
Labels: Valid commit message, PR approved

#1618 Security Patch (ASB) integration Oct-2022
  aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/external/dtc/01_0001-FROMGIT-libfdt-fdt_offset_ptr-Fix-comparison-warnings.bulletin.patch
  aosp_diff/preliminary/frameworks/av/14_0014-Cache-MMAP-client-silenced-state-.bulletin.patch
  aosp_diff/preliminary/frameworks/av/15_0015-Add-missing-bounds-checks.bulletin.patch
  aosp_diff/preliminary/frameworks/base/58_0058-Restrict-getInputMethodWindowVisibleHeight.bulletin.patch
  aosp_diff/preliminary/frameworks/base/59_0059-Block-FullScreenIntent-while-device-is-in-use-if-notificatio.bulletin.patch
  aosp_diff/preliminary/frameworks/base/60_0060-Fix-Notification-redaction-when-power-cycling-a-non-dozing-d.bulletin.patch
  aosp_diff/preliminary/frameworks/base/61_0061-DO-NOT-MERGE-Exclude-TYPE_PRIVATE_PRESENTATION-app-visibli.bulletin.patch
  aosp_diff/preliminary/frameworks/base/62_0062-Enforce-zen-rule-limit-on-a-package-level-.bulletin.patch
  aosp_diff/preliminary/hardware/interfaces/10_0010-Fix-array-out-of-bound-in-audioTransportToHal-.bulletin.patch
  aosp_diff/preliminary/packages/providers/ContactsProvider/02_0002-enforce-stricter-CallLogProvider-query.bulletin.patch
  aosp_diff/preliminary/system/bt/13_0013-Fix-potential-interger-overflow-when-parsing-vendor-response.bulletin.patch
  aosp_diff/preliminary/system/nfc/04_0004-The-length-of-a-packet-should-be-non-zero.bulletin.patch
Labels: Valid commit message

#1621 Security Patch (ASB) integration Oct-2022
  aosp_diff/preliminary/build/make/0004-Update-Security-patch-level.patch
  aosp_diff/preliminary/external/dtc/0001--automerge-FROMGIT-libfdt-fdt_offset_ptr-Fix-compariso.bulletin.patch
  aosp_diff/preliminary/frameworks/av/0004-Cache-MMAP-client-silenced-state-.bulletin.patch
  aosp_diff/preliminary/frameworks/av/0005-Add-missing-bounds-checks.bulletin.patch
  aosp_diff/preliminary/frameworks/base/05_0005-Perform-the-user-allowlist-check-after-all-other-fixed-allow.bulletin.patch
  aosp_diff/preliminary/frameworks/base/06_0006-Fix-Notification-redaction-when-power-cycling-a-non-dozing-d.bulletin.patch
  aosp_diff/preliminary/frameworks/base/07_0007-Block-FullScreenIntent-while-device-is-in-use-if-notificatio.bulletin.patch
  aosp_diff/preliminary/frameworks/base/08_0008-Strip-transition-information-from-activityoptions-when-sent-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/09_0009-Enforce-zen-rule-limit-on-a-package-level-.bulletin.patch
  aosp_diff/preliminary/hardware/interfaces/10_0010-Fix-array-out-of-bound-in-audioTransportToHal-.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0003-Fix-potential-interger-overflow-when-parsing-vendor-response.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0004-Reconfigure-Address-policy-on-last-bond-removed.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0005-Ignore-calls-to-set-the-address-policy-after-it-has-already-.bulletin.patch
  aosp_diff/preliminary/system/nfc/01_0001-The-length-of-a-packet-should-be-non-zero.bulletin.patch
Labels: Valid commit message
