Repository projectceladon/vendor-intel-utils, pull requests merged in 2023-12, with the labels that each got.

#2233 Don't let SystemUpdater app access files on Udisk
  aosp_diff/preliminary/bootable/recovery/03_0003-Modify-systemupdatersample-to-support-OTA-from-U-dis.patch
Labels: PR approved

#2214 Update diff patches due to v6.1.61 kernel rebase
  bsp_diff/common/kernel/lts2022-chromium/0004-iwlwifi-Get-driver-and-firmware-version-vendor-comma.patch
  bsp_diff/common/kernel/lts2022-chromium/0007-Fix-build-issue-in-wifi-driver.patch
Labels: Valid commit message, PR approved

#2223 Fix IndexOutOfBoundsException on com.android.car.media.localmediaplayer
  aosp_diff/preliminary/packages/apps/Car/LocalMediaPlayer/0002-Fix-IndexOutOfBoundsException-on-LocalMediaPlayer.patch
Labels: Valid commit message, PR approved

#2222 Fix fragment java crash on com.android.deskclock
  aosp_diff/preliminary/packages/apps/DeskClock/0002-Fix-fragment-java-crash-on-com.android.deskclock.patch
Labels: Valid commit message, PR approved

#2245 Update kernel and utils commit hash in host kernel build script
  host/kernel/lts2022-chromium/build_weekly.sh
  host/kernel/lts2022-chromium/x86_64_defconfig
Labels: PR approved

#2249 Update utils commit hash in host kernel build script
  host/kernel/lts2022-chromium/build_weekly.sh
Labels: Valid commit message, PR approved

#2231 ASB - December 2023 Security Patches integration
  aosp_diff/common/build/make/0002-Updating-Platform-Security-version.patch
  aosp_diff/common/frameworks/av/0023-httplive-fix-use-after-free.bulletin.patch
  aosp_diff/common/frameworks/av/0024--RESTRICT-AUTOMERGE-Update-uid-state-based-on-capability-field.bulletin.patch
  aosp_diff/common/frameworks/base/0223-On-device-lockdown-always-show-the-keyguard.bulletin.patch
  aosp_diff/common/frameworks/base/0224-Visit-Uris-added-by-WearableExtender.bulletin.patch
  aosp_diff/common/frameworks/base/0225-Fix-bypass-BAL-via-requestGeofence-.bulletin.patch
  aosp_diff/common/frameworks/base/0226-Visit-Uris-related-to-Notification-style-extras.bulletin.patch
  aosp_diff/common/frameworks/base/0227-RESTRICT-AUTOMERGE-Drop-invalid-data-.bulletin.patch
  aosp_diff/common/frameworks/base/0228-Validate-URI-based-shortcut-icon-at-creation-time-.bulletin.patch
  aosp_diff/common/frameworks/base/0229-Require-permission-to-unlock-keyguard.bulletin.patch
  aosp_diff/common/frameworks/base/0230-Restrict-number-of-shortcuts-can-be-added-through-addDynamicShor.bulletin.patch
  aosp_diff/common/frameworks/base/0231-Use-readUniqueFileDescriptor-in-incidentd-service.bulletin.patch
  aosp_diff/common/frameworks/base/0232-Revert-On-device-lockdown-always-show-the-keyguard-.bulletin.patch
  aosp_diff/common/frameworks/base/0233-Revert-On-device-lockdown-always-show-the-keyguard-.bulletin.patch
  aosp_diff/common/frameworks/base/0234-Updated-always-show-the-keyguard-on-device-lockdown.bulletin.patch
  aosp_diff/common/frameworks/base/0235-RESTRICT-AUTOMERGE-Check-URI-permissions-for-resumab.patch
  aosp_diff/common/packages/apps/Bluetooth/0004-Fix-UAF-in-CallbackEnv.bulletin.patch
  aosp_diff/common/packages/apps/Launcher3/0003-Fix-permission-bypass-in-legacy-shortcut.bulletin.patch
  aosp_diff/common/packages/services/Telecomm/0015-Resolve-account-image-icon-profile-boundary-exploit-.bulletin.patch
  aosp_diff/common/system/bt/0033-Reject-access-to-secure-service-authenticated-from-a-temp-bondin.bulletin.patch
  aosp_diff/common/system/bt/0034-Reject-access-to-secure-services-authenticated-from-temp-bonding.bulletin.patch
  aosp_diff/common/system/bt/0035-Reorganize-the-code-for-checking-auth-requirement.bulletin.patch
  aosp_diff/common/system/bt/0036-Enforce-authentication-if-encryption-is-required.bulletin.patch
  aosp_diff/common/system/bt/0037-Reject-access-to-secure-service-authenticated-from-a-temp-bondi.bulletin.patch
  aosp_diff/common/system/bt/0038-Add-bounds-checks-in-btif_avrcp_audio_track-cc.bulletin.patch
  aosp_diff/common/system/bt/0039-Fix-timing-attack-in-BTM_BleVerifySignature.bulletin.patch
  aosp_diff/common/system/netd/0001-Fix-Heap-use-after-free-in-MDnsSdListener-Monitor-run.bulletin.patch
Labels: Valid commit message, PR approved

#2254 Fix conflict
  bsp_diff/base_aaos/hardware/intel/kernelflinger/0001-REVERT-ME-Set-device-as-unlocked-state-by-default-on.patch
Labels: Valid commit message, PR approved

#2257 Aosp r17
  aosp_diff/preliminary/external/angle/0001-Build-external-angle-by-python3.patch
Labels: Valid commit message, PR approved

#2252 Fixed for Crashes in Gallery App.
  aosp_diff/base_aaos/packages/apps/Gallery2/0005-Fixed-for-Crashes-in-Gallery-App.patch
Labels: Valid commit message, PR approved

#2260 Fixed for Crashes During Monkey Test.
  aosp_diff/base_aaos/packages/apps/Contacts/0001-Fixed-for-Crash-in-Contact-app-during-Monkey-Test.patch
  aosp_diff/base_aaos/packages/services/Car/0018-Fixed-for-Crash-in-KitchenSink-app-During-Monkey-Tes.patch
Labels: Valid commit message, PR approved

#2259 drm/i915: Fix i915 crash issue
  bsp_diff/base_aaos/kernel/linux-intel-lts2021/0034-drm-i915-Fix-i915-crash-issue.patch
Labels: PR approved

#2266 Fixed for crashes during Monkey test run.
  aosp_diff/base_aaos/packages/apps/Car/Media/0002-Fixed-for-Media-crash-during-Monkey-Test-Run.patch
  aosp_diff/base_aaos/packages/apps/Car/libs/0003-Fixed-for-Media-crash-during-Monkey-Test-Run.patch
  aosp_diff/base_aaos/packages/services/Car/0019-Fixed-for-Crash-in-MD-Launcher-during-Monkey-Test.patch
Labels: Valid commit message, PR approved

#2272 Fixed for Soft Keyboard Color & key size.
  aosp_diff/base_aaos/packages/apps/Car/LatinIME/0001-Fixed-for-Soft-Keyboard-Color-key-size.patch
Labels: Valid commit message, PR approved

#2274 Fix Bluetooth stability issues
  aosp_diff/base_aaos/packages/apps/Bluetooth/0006-Fix-a2dp-state-machine-crash-during-stability-testin.patch
  aosp_diff/base_aaos/system/bt/49_0049-Fix-crash-when-bt-headset-connects-on-aux-BT.patch
  aosp_diff/base_aaos/system/bt/50_0050-Fix-metadata-issue-when-reconnect-pixel.patch
  bsp_diff/base_aaos/vendor/linux/firmware/0004-Upgrade-fw-for-Bluetooth-AX210.patch
Labels: Valid commit message, PR approved

#2262 add flag to skip removing permissions at cleardata
  aosp_diff/preliminary/frameworks/base/99_0224-add-flag-to-skip-removing-permissions-in-clearApplic.patch
Labels: Valid commit message, PR approved

#2239 Clean-up Utils folder
  bsp_diff/caas/device/intel/mixins/.0003-Enable-omx-service-although-hal-is-deprecated.patch.swp
  bsp_diff/caas/device/intel/mixins/0001-Upgrading-API-to-34-for-android-U.patch
  bsp_diff/caas/device/intel/mixins/0002-Enable-drm-aidl-service.patch
  bsp_diff/caas/device/intel/mixins/0003-Enable-omx-service-although-hal-is-deprecated.patch
  bsp_diff/common/device/intel/mixins/0001-Enable-graphics.composer3-AIDL-HAL-service-in-Androi.patch
Labels: Valid commit message

#2264 ASB-January 2024 Security Patches integration
  aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/av/0025-Codec2BufferUtils-Use-cropped-dimensions-in-RGB-to-YUV-conversi.bulletin.patch
  aosp_diff/preliminary/frameworks/av/0026-Fix-convertYUV420Planar16ToY410-overflow-issue-for-unsupported-c.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0157-DO-NOT-MERGE-Ensure-finish-lockscreen-when-usersetup.patch
  aosp_diff/preliminary/frameworks/base/99_0158--SB-Privacy-Fetch-current-active-appops-on-startup-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Camera2/04_0004-Camera2-Do-not-pass-location-info-for-startActivity-case.bulletin.patch
  aosp_diff/preliminary/packages/apps/Nfc/0002-Possible-deadlock-on-the-NfcService-object.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/0023-Make-sure-work-profile-app-cant-enable-notification-listener-ser.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/0024-Validate-ringtone-URIs-before-setting.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0049-Fix-some-OOB-errors-in-BTM-parsing.bulletin.patch
  aosp_diff/preliminary/packages/modules/NeuralNetworks/0005-Fix-OOB-Read-in-convertSubgraphFromHAL.bulletin.patch
Labels: Valid commit message, PR approved

#2270 ASB - January 2024 Security Patches integration
  aosp_diff/common/build/make/0002-Updating-Platform-Security-version.patch
  aosp_diff/common/frameworks/av/0025-Codec2BufferUtils-Use-cropped-dimensions-in-RGB-to-YUV-conversi.bulletin.patch
  aosp_diff/common/frameworks/av/0026-Fix-convertYUV420Planar16ToY410-overflow-issue-for-unsupported-c.bulletin.patch
  aosp_diff/common/frameworks/base/0236-Add-placeholder-when-media-control-title-is-blank.patch
  aosp_diff/common/frameworks/base/0237-DO-NOT-MERGE-Ensure-finish-lockscreen-when-usersetup-incomplete.bulletin.patch
  aosp_diff/common/frameworks/base/0238-Fix-vulnerability-that-allowed-attackers-to-start-arbitary-activ.bulletin.patch
  aosp_diff/common/packages/apps/Camera2/0001-Camera2-Do-not-pass-location-info-for-startActivity-case.bulletin.patch
  aosp_diff/common/packages/apps/Nfc/0005-Possible-deadlock-on-the-NfcService-object.bulletin.patch
  aosp_diff/common/packages/apps/Settings/0037-Validate-ringtone-URIs-before-setting.bulletin.patch
  aosp_diff/common/system/bt/0040-Fix-some-OOB-errors-in-BTM-parsing.bulletin.patch
Labels: Valid commit message, PR approved

#2265 Refine previous patch for fixing i915 crash issue
  bsp_diff/base_aaos/kernel/linux-intel-lts2021/0034-drm-i915-Fix-i915-crash-issue.patch
Labels: Valid commit message, PR approved
