Repository projectceladon/vendor-intel-utils, pull requests merged in 2023-05, with the labels that each got.

#1864 Fix for AOSP and EVS cameras not working
  aosp_diff/celadon_ivi/packages/services/Car/0004-Fix-for-AOSP-and-EVS-cameras-not-working.patch
  aosp_diff/celadon_ivi/packages/services/Car/0005-Fix-EVS-sample-driver-not-getting-started-as-service.patch
Labels: Valid commit message, PR approved

#1865 Merging the ASB patches for May 2023
  aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/base/68_0068--RESTRICT-AUTOMERGE-pm-prevent-system-app-downgrades-of-ve.bulletin.patch
  aosp_diff/preliminary/frameworks/base/69_0069--RESTRICT-AUTOMERGE-pm-still-allow-debuggable-for-system-a.bulletin.patch
  aosp_diff/preliminary/frameworks/base/70_0070-Checks-if-AccessibilityServiceInfo-is-within-parcelable-size.bulletin.patch
  aosp_diff/preliminary/frameworks/base/71_0071-enforce-stricter-rules-when-registering-phoneAccounts.bulletin.patch
  aosp_diff/preliminary/frameworks/base/72_0072-DO-NOT-MERGE-Isolated-processes-must-fail-registering-BRs-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/73_0073-Limit-the-number-of-shortcuts-per-app-that-can-be-retained-b.bulletin.patch
  aosp_diff/preliminary/frameworks/base/74_0074-Re-enforce-MANAGE_ACTIVITY_TASKS-for-applySyncTransa.patch
  aosp_diff/preliminary/frameworks/base/75_0075-Trim-strings-added-to-persistent-snoozed-notificatio.patch
  aosp_diff/preliminary/frameworks/native/04_0004-Check-for-malformed-Sensor-Flattenable.bulletin.patch
  aosp_diff/preliminary/frameworks/native/05_0005-Remove-some-new-memory-leaks-from-SensorManager.bulletin.patch
  aosp_diff/preliminary/frameworks/native/06_0006-Add-removeInstanceForPackageMethod-to-SensorManager.bulletin.patch
  aosp_diff/preliminary/hardware/nxp/nfc/0005-OOBR-in-AnalyzeMfcResp-in-NxpMfcReader-cc.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/0013--DO-NOT-MERGE-Enforce-INTERACT_ACROSS_USERS_FULL-permission.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/0008-enforce-stricter-rules-when-registering-phoneAccounts.bulletin.patch
Labels: Valid commit message, PR approved

#1856 Show IP address in car settings
  aosp_diff/celadon_ivi/packages/apps/Car/Settings/02_0002-Show-IP-address-in-car-settings.patch
Labels: Valid commit message, PR approved

#1868 Update build_weekly.sh with latest commit tag for
  host/kernel/linux-intel-lts2021/build_weekly.sh
Labels: Valid commit message, PR approved

#1872 CVE-2023-20910 has been removed from the 2023-03-01 SPL
  aosp_diff/preliminary/packages/modules/Wifi/0005--Passpoint-Add-more-check-to-limit-the-config-size.bulletin.patch
Labels: Valid commit message, PR approved

#1880 Force stop bootanimation when CarLauncher UI ready
  aosp_diff/celadon_ivi/packages/services/Car/0006-WA-Force-stop-bootanimation-when-CarLauncher-UI-read.patch
Labels: PR approved

#1893 Delete Runchecks.yaml
  .github/workflows/Runchecks.yaml
Labels: Invalid commit message

#1895 Add allowZip64=True for ZipFile in RebuildAndWriteSuperImages
  aosp_diff/preliminary/build/make/0005-Add-allowZip64-True-for-ZipFile-in-RebuildAndWriteSu.patch
Labels: Valid commit message, PR approved

#1896 ASB - Security Patch integration June 2023
  aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/av/0014-Fix-NuMediaExtractor-readSampleData-buffer-Handling.bulletin.patch
  aosp_diff/preliminary/frameworks/base/76_0076-Prevent-sharesheet-from-previewing-unowned-URIs.patch
  aosp_diff/preliminary/frameworks/base/77_0077--DO-NOT-MERGE-Wait-for-preloading-images-to-complete-before.bulletin.patch
  aosp_diff/preliminary/frameworks/base/78_0078-Prevent-RemoteViews-crashing-SystemUi.patch
  aosp_diff/preliminary/frameworks/base/79_0079-Check-key-intent-for-selectors-and-prohibited-flags.bulletin.patch
  aosp_diff/preliminary/frameworks/base/80_0080-Use-PendingIntent-for-media-click-action-over-locksc.patch
  aosp_diff/preliminary/frameworks/base/81_0081-Allow-filtering-of-services.bulletin.patch
  aosp_diff/preliminary/frameworks/base/82_0082-Enforce-DevicePolicyManager-setUserControlDisabledPackages-i.bulletin.patch
  aosp_diff/preliminary/frameworks/base/83_0083-Add-BubbleMetadata-detection-to-block-FSI.patch
  aosp_diff/preliminary/frameworks/base/84_0084-Fix-issues-with-setRemotePlaybackInfo.patch
  aosp_diff/preliminary/frameworks/base/85_0085--RESTRICT-AUTOMERGE-Fix-test-failure-caused-by-incorrect-st.bulletin.patch
  aosp_diff/preliminary/packages/apps/Car/Settings/0001--automerge-Convert-argument-to-Intent-in-car-settings-accou.bulletin.patch
  aosp_diff/preliminary/packages/apps/Car/Settings/0002-Convert-argument-to-Intent-in-car-settings-AddAccountActivit.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/0014-Convert-argument-to-intent-in-AddAccountSettings-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/0015-Don-t-show-NLSes-with-excessively-long-component-names.bulletin.patch
  aosp_diff/preliminary/packages/apps/Traceur/0001-Update-Traceur-to-check-admin-user-status.bulletin.patch
  aosp_diff/preliminary/packages/apps/Traceur/0002-Add-DISALLOW_DEBUGGING_FEATURES-check.bulletin.patch
  aosp_diff/preliminary/packages/apps/TvSettings/0001-Convert-argument-to-intent-in-addAccount-TvSettings-.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0029-Fix-OOB-read-in-btm_ble_periodic_av_sync_lost.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0030-Revert-Revert-Validate-buffer-length-in-sdpu_build_uuid_se.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/0005--TOFU-Don-t-send-credentials-in-an-unauthenticated-TLS-tunn.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/0006-Revert-TOFU-Don-t-send-credentials-in-an-unauthenticated-.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/0007--TOFU-Implement-a-secure-TOFU-flow.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/0009-Call-Redirection-unbind-service-when-onBind-returns-null.bulletin.patch
Labels: Valid commit message, PR approved

#1901 Add allowZip64=True for ZipFile in RebuildAndWriteSuperImages
  aosp_diff/preliminary/build/tools/03_0003-Add-allowZip64-True-for-ZipFile-in-RebuildAndWriteSu.patch
Labels: Valid commit message, PR approved

#1834 remove unknown kernel cmdline buildvariant
  aosp_diff/celadon_ivi/build/core/0001-remove-unknown-kernel-cmdline-buildvariant.patch
Labels: PR approved

#1899 ASB - Security Patch integration June 2023
  aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/av/23_0023-Fix-NuMediaExtractor-readSampleData-buffer-Handling.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0149-Prevent-sharesheet-from-previewing-unowned-URIs.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0150--DO-NOT-MERGE-Wait-for-preloading-images-to-complete-before.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0151--DO-NOT-MERGE-Prevent-RemoteViews-crashing-SystemUi.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0152-Grant-MANAGE_USERS-access-to-Traceur.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0153-Check-key-intent-for-selectors-and-prohibited-flags.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0154-Handle-invalid-data-during-job-loading-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0155-Allow-filtering-of-services.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0156-Enforce-DevicePolicyManager-setUserControlDisabledPackages-i.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0157--RESTRICT-AUTOMERGE-Add-BubbleMetadata-detection-to-block-F.bulletin.patch
  aosp_diff/preliminary/packages/apps/Car/Settings/0002-Convert-argument-to-Intent-in-car-settings-account-removal-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Car/Settings/0003-Convert-argument-to-Intent-in-car-settings-AddAccountActivit.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/27_0027--Settings-Move-display-of-VPN-version-into-summary-text.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/28_0028-Import-translations.-DO-NOT-MERGE-ANYWHERE.patch
  aosp_diff/preliminary/packages/apps/Settings/29_0029-Convert-argument-to-intent-in-AddAccountSettings-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/30_0030-Don-t-show-NLSes-with-excessively-long-component-names.bulletin.patch
  aosp_diff/preliminary/packages/apps/Traceur/0001-Update-Traceur-to-check-admin-user-status.patch
  aosp_diff/preliminary/packages/apps/Traceur/0002-Add-DISALLOW_DEBUGGING_FEATURES-check.bulletin.patch
  aosp_diff/preliminary/packages/apps/TvSettings/0001-Convert-argument-to-intent-in-addAccount-TvSettings-.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/10_0010-Call-Redirection-unbind-service-when-onBind-returns-null.bulletin.patch
  aosp_diff/preliminary/system/bt/31_0031-Prevent-use-after-free-of-HID-reports.bulletin.patch
  aosp_diff/preliminary/system/bt/32_0032-Revert-2-Validate-buffer-length-in-sdpu_build_uuid_seq-.bulletin.patch
  aosp_diff/preliminary/system/bt/33_0033-Revert-Revert-Fix-wrong-BR-EDR-link-key-downgrades-P_256-.bulletin.patch
Labels: PR approved
