Repository projectceladon/vendor-intel-utils, pull requests merged in 2023-08, with the labels that each got.

#2022 updating dummy cpufreq_frequency_table
  bsp_diff/common/kernel/linux-intel-lts2021/0019-updating-dummy-cpufreq_frequency_table.patch
  bsp_diff/common/kernel/lts2021-chromium/0023-updating-dummy-cpufreq_frequency_table.patch
Labels: Valid commit message, PR approved

#2021 no need to exec the wait_for_keymaster
  bsp_diff/celadon_ivi/device/intel/mixins/0004-no-need-to-exec-wait_for_keymaster.patch
Labels: Valid commit message

#2034 Fixed for crash in webview_shell during monkey test.
  aosp_diff/preliminary/frameworks/base/99_0175-Fixed-for-crash-in-webview_shell-during-monkey-test.patch
Labels: Valid commit message, PR approved

#2036 Fixed for crash in Local media player during monkey test.
  aosp_diff/celadon_ivi/packages/apps/Car/LocalMediaPlayer/0001-Fixed-for-crash-in-Local-media-player-during-monkey-.patch
Labels: Valid commit message, PR approved

#2038 Fixed for crash in Alert Dialog Builder during monkey test.
  aosp_diff/celadon_ivi/packages/apps/Car/libs/0002-Fixed-for-crash-in-Alert-Dialog-Builder-during-monke.patch
Labels: Valid commit message, PR approved

#1983 Fix virtio2d cannot start issue on smr0 master
  bsp_diff/common/kernel/lts2020-yocto/0044-Add-module-parameter-for-virtio2d-3d-distinction.patch
  bsp_diff/common/kernel/lts2020-yocto/0045-Fix-virtio2d-color-r-b-reversed-issue.patch
Labels: Valid commit message, PR approved

#2030 Fix for static analysis issues
  bsp_diff/common/vendor/intel/external/project-celadon/mediasdk-omx/0008-Fix-for-static-analysis-issues.patch
Labels: PR approved

#2025 Fix for crash seen in kog demo screen
  bsp_diff/common/hardware/intel/gmmlib/0001-Enable-compilation-on-android.patch
  bsp_diff/common/hardware/intel/media-driver/0001-Add-changes-to-build-latest-media-driver-in-Android.patch
  bsp_diff/common/hardware/intel/media-driver/0003-WA-Disable-m_blokCopyon-to-address-crash-in-KOG.patch
Labels: PR approved

#2044 Fix crash on EmbeddedKitchenSink.
  aosp_diff/celadon_ivi/packages/services/Car/0014-Fix-crash-on-EmbeddedKitchenSink.patch
Labels: Valid commit message, PR approved

#1998 Add protection on LocalMedia to avoid monkey crash.
  aosp_diff/celadon_ivi/packages/apps/Car/LocalMediaPlayer/0001-WA-Add-protection-on-LocalMedia-to-avoid-monkey-cras.patch
Labels: Valid commit message, PR approved

#2013 ASB - Security Patch integration August 2023
  aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/external/aac/0001-Increase-patchParam-array-size-by-one-and-fix-out-of-bounce-.bulletin.patch
  aosp_diff/preliminary/external/freetype/0003-Cherrypick-following-three-changes.bulletin.patch
  aosp_diff/preliminary/frameworks/base/55_0055-Enforce-MediaButtonReceiver-extracted-component-name-matches.bulletin.patch
  aosp_diff/preliminary/frameworks/base/57_0057-Enforce-MediaButtonReceiver-ComponentName-belongs-to-app.bulletin.patch
  aosp_diff/preliminary/frameworks/base/97_0097-ActivityManagerService-Allow-openContentUri-from-vendor-sys.bulletin.patch
  aosp_diff/preliminary/frameworks/base/98_0098-Do-not-load-drawable-for-wallet-card-if-the-card-image-icon-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0099-Ensure-policy-has-no-absurdly-long-strings.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0100-On-device-lockdown-always-show-the-keyguard.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0101-Preserve-flags-for-non-runtime-permissions-upon-package-upda.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0102-Check-URIs-in-notification-public-version.patch
  aosp_diff/preliminary/frameworks/base/99_0103-Implement-visitUris-for-RemoteViews-ViewGroupActionAdd-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0104-Validate-ComponentName-for-MediaButtonBroadcastReceiver.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0105-Fix-PrivacyChip-not-visible-issue.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0106-Update-Pip-launches-to-not-enter-pinned-task-if-in-backgroun.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0107-Check-URIs-in-sized-remote-views-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0108-Visit-URIs-in-themed-remoteviews-icons-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0109-DO-NOT-MERGE-Verify-URI-permissions-in-MediaMetadata.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0110-Use-Settings-System-getIntForUser-instead-of-getInt-to-make-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0111-Remove-unnecessary-padding-code.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0112-Merge-Resolve-StatusHints-image-exploit-across-user-into-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0113-Support-test-skipping-when-power-save-modes-aren-t-e.patch
  aosp_diff/preliminary/packages/apps/ManagedProvisioning/0001-Remove-factory-reset-logic-from-post-suw-syncauth.bulletin.patch
  aosp_diff/preliminary/packages/modules/NeuralNetworks/0002-Fix-OOB-Read-in-setOperandValue.bulletin.patch
  aosp_diff/preliminary/packages/modules/NeuralNetworks/0003-Fix-OOB-read-in-parseInputs-in-ShimPreparedModel-cpp.bulletin.patch
  aosp_diff/preliminary/packages/modules/Permission/0001-RESTRICT-AUTOMERGE-Finish-ManagePermissionsActivity-if-devic.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/0010--TOFU-Validate-full-cert-chains-before-displaying-dialog.bulletin.patch
  aosp_diff/preliminary/packages/providers/TelephonyProvider/0002-Update-file-permissions-using-canonical-path.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/0010--conflict-Resolve-StatusHints-image-exploit-across-user-am.bulletin.patch
  aosp_diff/preliminary/system/ca-certificates/0001-Drop-TrustCor-certificates.bulletin.patch
Labels: Valid commit message, PR approved

#2042 Add virtio tiling mode support for SRIOV
  bsp_diff/caas/kernel/lts2020-yocto/0001-drm-virtio-Improve-DMA-API-usage-for-shmem-BOs.patch
  bsp_diff/caas/kernel/lts2020-yocto/0002-virtio-gpu-api-multiple-context-types-with-explicit-.patch
  bsp_diff/caas/kernel/lts2020-yocto/0003-drm-virtio-implement-context-init-probe-for-feature.patch
  bsp_diff/caas/kernel/lts2020-yocto/0004-drm-introduce-fb_modifiers_not_supported-flag-in-mod.patch
  bsp_diff/caas/kernel/lts2020-yocto/0005-drm-virtio-set-fb_modifiers_not_supported.patch
  bsp_diff/caas/kernel/lts2020-yocto/0006-drivers-virtgpu-Add-support-for-gem-buffer-import.patch
  bsp_diff/caas/kernel/lts2020-yocto/0007-drivers-virtgpu-Add-virtio-gpu-tiling-format-support.patch
  host/qemu/0036-dm-virtio-gpu-Add-virtio-gpu-plane-format-modifier-s.patch
Labels: Invalid commit message, PR approved

#2023 Fix "Loading" dialog not hidden timely after user SWITCHING event
  aosp_diff/celadon_ivi/packages/apps/Car/SystemUI/0001-Fix-Loading-dialog-not-hidden-timely-after-user-SWIT.patch
Labels: Valid commit message, PR approved, Developer Approved

#2020 ASB - Security Patch integration August 2023
  aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/external/aac/02_0002-Increase-patchParam-array-size-by-one-and-fix-out-of-bounce-.bulletin.patch
  aosp_diff/preliminary/external/freetype/0002-Cherrypick-following-three-changes.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0175-ActivityManagerService-Allow-openContentUri-from-vendor-sys.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0176-Do-not-load-drawable-for-wallet-card-if-the-card-image-icon-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0177-On-device-lockdown-always-show-the-keyguard.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0178-Ensure-policy-has-no-absurdly-long-strings.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0179-Preserve-flags-for-non-runtime-permissions-upon-package-upda.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0180-Check-URIs-in-notification-public-version.patch
  aosp_diff/preliminary/frameworks/base/99_0181-Implement-visitUris-for-RemoteViews-ViewGroupActionAdd-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0182-Validate-ComponentName-for-MediaButtonBroadcastReceiver.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0183-Verify-URI-permissions-in-MediaMetadata.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0184-Check-URIs-in-sized-remote-views-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0185-Fix-PrivacyChip-not-visible-issue.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0186-Visit-URIs-in-themed-remoteviews-icons-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0187-Resolve-StatusHints-image-exploit-across-user-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0188-Use-Settings-System-getIntForUser-instead-of-getInt-to-make-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0189-Remove-unnecessary-padding-code.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0190-Support-test-skipping-when-power-save-modes-aren-t-e.patch
  aosp_diff/preliminary/frameworks/base/99_0191-Fix-for-ASB-Aug-2023-build-error.patch
  aosp_diff/preliminary/packages/apps/ManagedProvisioning/03_0003-Remove-factory-reset-logic-from-post-suw-syncauth.bulletin.patch
  aosp_diff/preliminary/packages/modules/NeuralNetworks/0004-Fix-OOB-Read-in-setOperandValue.bulletin.patch
  aosp_diff/preliminary/packages/modules/NeuralNetworks/0005-Fix-OOB-read-in-parseInputs-in-ShimPreparedModel-cpp.bulletin.patch
  aosp_diff/preliminary/packages/modules/Permission/06_0006-RESTRICT-AUTOMERGE-Finish-ManagePermissionsActivity-if-devic.bulletin.patch
  aosp_diff/preliminary/packages/providers/TelephonyProvider/0002-Update-file-permissions-using-canonical-path.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/11_0011-Resolve-StatusHints-image-exploit-across-user-.bulletin.patch
  aosp_diff/preliminary/system/ca-certificates/0001-Drop-TrustCor-certificates.bulletin.patch
Labels: Valid commit message, PR approved

#2019 ASB - Security Patch integration August 2023
  aosp_diff/common/build/make/0002-Updating-Platform-Security-version.patch
  aosp_diff/common/external/aac/0002-Increase-patchParam-array-size-by-one-and-fix-out-of-bounce-.bulletin.patch
  aosp_diff/common/external/freetype/0002-Cherrypick-following-three-changes.bulletin.patch
  aosp_diff/common/frameworks/base/0189-ActivityManagerService-Allow-openContentUri-from-vendor-sys.bulletin.patch
  aosp_diff/common/frameworks/base/0190-On-device-lockdown-always-show-the-keyguard.bulletin.patch
  aosp_diff/common/frameworks/base/0191-Ensure-policy-has-no-absurdly-long-strings.bulletin.patch
  aosp_diff/common/frameworks/base/0192-Implement-visitUris-for-RemoteViews-ViewGroupActionAdd-.bulletin.patch
  aosp_diff/common/frameworks/base/0193-Check-URIs-in-notification-public-version.patch
  aosp_diff/common/frameworks/base/0194-Verify-URI-permissions-in-MediaMetadata.bulletin.patch
  aosp_diff/common/frameworks/base/0195-Use-Settings-System-getIntForUser-instead-of-getInt-to-make-.bulletin.patch
  aosp_diff/common/frameworks/base/0196-Resolve-StatusHints-image-exploit-across-user-.bulletin.patch
  aosp_diff/common/packages/apps/QuickAccessWallet/0001-Do-not-load-drawable-for-wallet-card-if-the-card-image-icon-.bulletin.patch
  aosp_diff/common/packages/providers/TelephonyProvider/0002-Update-file-permissions-using-canonical-path.bulletin.patch
  aosp_diff/common/packages/services/Telecomm/0012-Resolve-StatusHints-image-exploit-across-user-.bulletin.patch
  aosp_diff/common/system/ca-certificates/0001-Drop-TrustCor-certificates.bulletin.patch
Labels: PR approved

#2048 Removing the patch as it is causing lunch conflict
  aosp_diff/preliminary/frameworks/base/22_0022-Keyguard-Treat-messsages-to-lock-with-priority.patch
  aosp_diff/preliminary/frameworks/base/99_0191-Fix-for-ASB-Aug-2023-build-error.patch
Labels: Valid commit message, PR approved, Developer Approved

#2037 Fixed for crash in Gallery during monkey test.
  aosp_diff/preliminary/packages/apps/Gallery2/0001-Fixed-for-crash-in-Gallery-during-monkey-test.patch
Labels: Valid commit message, PR approved

#2054 Support x86 for optee_client Android integration
  bsp_diff/celadon_ivi/vendor/intel/optee/optee_client/0001-Support-Android-integration-on-x86.patch
Labels: PR approved

#2060 ASB - Security Patch integration September 2023
  aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/av/25_0025-Fix-Segv-on-unknown-address-error-flagged-by-fuzzer-test-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/61_0061-DO-NOT-MERGE-Exclude-TYPE_PRIVATE_PRESENTATION-app-visibli.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99-0195-Improve-user-handling-when-querying-for-resumable-media.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0191--DO-NOT-MERGE-Update-quickshare-intent-rather-than-recreati.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0192-Ignore-virtual-presentation-windows-RESTRICT-AUTOMERGE.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0193-Forbid-granting-access-to-NLSes-with-too-long-component-name.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0194-Update-AccountManagerService-checkKeyIntentParceledCorrectly.bulletin.patch
  aosp_diff/preliminary/frameworks/native/17_0017-Allow-sensors-list-to-be-empty.bulletin.patch
  aosp_diff/preliminary/packages/apps/Launcher3/03_0003-Fix-permission-issue-in-legacy-shortcut.bulletin.patch
  aosp_diff/preliminary/packages/apps/Nfc/0001-Ensure-that-SecureNFC-setting-cannot-be-bypassed.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/32_0032-Don-t-hide-approved-NLSes-in-Settings.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/33_0033-DO-NOT-MERGE-Prevent-non-system-IME-from-becoming-device-ad.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/34_0034-Settings-don-t-try-to-allow-NLSes-with-too-long-component-n.bulletin.patch
  aosp_diff/preliminary/packages/modules/NeuralNetworks/0006-Fix-out-of-Bounds-Read-in-convertSubgraphFromHAL-in-ShimConv.bulletin.patch
  aosp_diff/preliminary/packages/providers/MediaProvider/06_0006-Remove-invalid-surrogates-during-bindSelection.bulletin.patch
  aosp_diff/preliminary/packages/providers/MediaProvider/07_0007-Canonicalize-file-path-for-insertion-by-legacy-apps.bulletin.patch
  aosp_diff/preliminary/packages/services/Telephony/0003-Fixed-leak-of-cross-user-data-in-multiple-settings-.bulletin.patch
  aosp_diff/preliminary/system/bt/35_0035-Fix-an-integer-overflow-bug-in-avdt_msg_asmbl.bulletin.patch
  aosp_diff/preliminary/system/bt/36_0036-Fix-integer-overflow-in-build_read_multi_rsp.bulletin.patch
  aosp_diff/preliminary/system/bt/37_0037-Fix-potential-abort-in-btu_av_act-cc.bulletin.patch
  aosp_diff/preliminary/system/bt/38_0038-Fix-UAF-in-gatt_cl-cc.bulletin.patch
Labels: Valid commit message, PR approved
