Repository projectceladon/vendor-intel-utils, pull requests merged in 2023-06, with the labels that each got.

#1903 ASB - Security Patch integration June 2023
  aosp_diff/common/build/make/0002-Updating-Platform-Security-version.patch
  aosp_diff/common/frameworks/av/0019-Fix-NuMediaExtractor-readSampleData-buffer-Handling.bulletin.patch
  aosp_diff/common/frameworks/base/0166-Prevent-sharesheet-from-previewing-unowned-URIs.bulletin.patch
  aosp_diff/common/frameworks/base/0167--DO-NOT-MERGE-Wait-for-preloading-images-to-complete-before.bulletin.patch
  aosp_diff/common/frameworks/base/0168--DO-NOT-MERGE-Prevent-RemoteViews-crashing-SystemUi.bulletin.patch
  aosp_diff/common/frameworks/base/0169-Check-key-intent-for-selectors-and-prohibited-flags.bulletin.patch
  aosp_diff/common/frameworks/base/0170-Handle-invalid-data-during-job-loading-.bulletin.patch
  aosp_diff/common/frameworks/base/0171-Allow-filtering-of-services.bulletin.patch
  aosp_diff/common/frameworks/base/0172-Enforce-DevicePolicyManager.setUserControlDisabledPa.patch
  aosp_diff/common/frameworks/base/0173--RESTRICT-AUTOMERGE-Add-BubbleMetadata-detection-to-block-F.bulletin.patch
  aosp_diff/common/packages/apps/Car/Settings/02_0002-Convert-argument-to-Intent-in-car-settings-AddAccoun.patch
  aosp_diff/common/packages/apps/Settings/0028--Settings-Move-display-of-VPN-version-into-summary-text.bulletin.patch
  aosp_diff/common/packages/apps/Settings/0029-Import-translations.-DO-NOT-MERGE-ANYWHERE.patch
  aosp_diff/common/packages/apps/Settings/0030-Convert-argument-to-intent-in-AddAccountSettings-.bulletin.patch
  aosp_diff/common/packages/apps/Settings/0031-Don-t-show-NLSes-with-excessively-long-component-names.bulletin.patch
  aosp_diff/common/packages/apps/Traceur/0001-Update-Traceur-to-check-admin-user-status.patch
  aosp_diff/common/packages/apps/Traceur/0002-Add-DISALLOW_DEBUGGING_FEATURES-check.bulletin.patch
  aosp_diff/common/packages/apps/Traceur/0003-Update-Traceur-to-check-admin-user-status.patch
  aosp_diff/common/packages/apps/TvSettings/0001-Convert-argument-to-intent-in-addAccount-TvSettings-.bulletin.patch
  aosp_diff/common/packages/services/Telecomm/0011-Call-Redirection-unbind-service-when-onBind-returns-null.bulletin.patch
  aosp_diff/common/system/bt/0025-Prevent-use-after-free-of-HID-reports.bulletin.patch
  aosp_diff/common/system/bt/0026-Revert-Revert-RESTRICT-AUTOMERGE-Validate-buffer-length-.bulletin.patch
  aosp_diff/common/system/bt/0027-Revert-Revert-Fix-wrong-BR-EDR-link-key-downgrades-P_256-.bulletin.patch
Labels: PR approved

#1904 Upgrading AOSP to New Version android-13.0.0_r43.
  aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/base/14-0014-Do-not-send-new-Intent-to-non-exported-activity-when-navigat.bulletin.patch
  aosp_diff/preliminary/frameworks/base/30_0030-New-Pipeline-hide-VISIBILITY_SECRET-notifications-on-lock-s.bulletin.patch
  aosp_diff/preliminary/frameworks/base/36_0036-Add-safety-checks-on-KEY_INTENT-mismatch-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/41_0041--RESTRICT-AUTOMERGE-SettingsProvider-mem-limit-should-be-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/52_0052-RESTRICT-AUTOMERGE-Use-chain-start-token-in-performOpTransac.bulletin.patch
  aosp_diff/preliminary/frameworks/base/56_0056-Just-show-toast-on-clipboard-change-if-user-not-set-up.bulletin.patch
  aosp_diff/preliminary/frameworks/base/58_0058-Fix-for-Home-Button-When-Google-Assistant-is-disable.patch
  aosp_diff/preliminary/frameworks/base/75_0075-Trim-strings-added-to-persistent-snoozed-notificatio.patch
  aosp_diff/preliminary/frameworks/base/76_0076-Prevent-sharesheet-from-previewing-unowned-URIs.patch
  aosp_diff/preliminary/frameworks/base/78_0078-Prevent-RemoteViews-crashing-SystemUi.patch
  aosp_diff/preliminary/frameworks/base/80_0080-Use-PendingIntent-for-media-click-action-over-locksc.patch
  aosp_diff/preliminary/frameworks/base/83_0083-Add-BubbleMetadata-detection-to-block-FSI.patch
  aosp_diff/preliminary/frameworks/base/84_0084-Fix-issues-with-setRemotePlaybackInfo.patch
  aosp_diff/preliminary/frameworks/base/85_0085--RESTRICT-AUTOMERGE-Fix-test-failure-caused-by-incorrect-st.bulletin.patch
  aosp_diff/preliminary/hardware/interfaces/02_0002-Fix-audio-crash-issue.patch
  aosp_diff/preliminary/packages/apps/Launcher3/0001-Fix-for-Home-Button-When-Google-Assistant-is-disable.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0010-Added-max-buffer-length-check.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0012-Add-length-check-when-copy-AVDT-and-AVCT-packet.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0014-Fix-URI-check-in-BluetoothOppUtility-java.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0015-Rotate-advertising-set-addresses-on-IRK-change.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0017-Add-flag-to-toggle-IRK-rotation.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0018-Pass-IRK-rotation-flag-into-native.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0021-Add-bounds-check-in-avdt_scb_act-cc.bulletin.patch
Labels: Valid commit message

#1840 Animations are not displayed for few of options in Settings.
  aosp_diff/preliminary/packages/apps/Settings/0013-Animations-are-not-displayed-for-few-of-options-in-s.patch
Labels: Valid commit message, PR approved

#1907 update media stack to media 23.2.1 release (devel-647)
  bsp_diff/common/hardware/intel/gmmlib/0001-Add-Android.mk.patch
  bsp_diff/common/hardware/intel/libva/0001-Update-Android.mk-for-libva-2.18.0.patch
  bsp_diff/common/hardware/intel/libva/0002-Support-media-stack-on-specified-render-node.patch
  bsp_diff/common/hardware/intel/media-driver/0001-Add-changes-to-build-latest-media-driver-in-Android.patch
  bsp_diff/common/hardware/intel/media-driver/0002-Resolved-compilation-issue-for-media-driver.patch
  bsp_diff/common/hardware/intel/onevpl-intel-gpu/0001-Changes-for-OneVPL-integration.patch
  bsp_diff/common/hardware/intel/onevpl-intel-gpu/0002-Restore-SG1-as-a-VPL-platform.patch
  bsp_diff/common/hardware/intel/onevpl-intel-gpu/0003-Resolved-runtime-error-for-onevpl.patch
  bsp_diff/common/hardware/intel/onevpl-intel-gpu/0004-Remove-ITT-vtune-support.patch
  bsp_diff/common/hardware/intel/onevpl-intel-gpu/0005-Fix-for-HEVC-rendering-failing-with-usptream-ffmpeg.patch
  bsp_diff/common/hardware/intel/onevpl-intel-gpu/0006-Changes-to-be-in-sync-with-features-enabled-in-linux.patch
  bsp_diff/common/hardware/intel/onevpl-intel-gpu/0007-Enable-avx2.patch
  bsp_diff/common/hardware/intel/onevpl/0001-Changes-for-OneVPL-integration.patch
  bsp_diff/common/hardware/intel/onevpl/0002-Fix-for-HEVC-rendering-failing-with-usptream-ffmpeg.patch
Labels: PR approved

#1911 Expand audio framework max channel count to 24
  aosp_diff/preliminary/system/media/0002-Expand-audio-framework-max-channel-count-to-24.patch
Labels: Valid commit message, PR approved

#1912 Update CHange-id to fix lunch error
  bsp_diff/cic_cloud/vendor/intel/external/intel-gpu/mesa/0007-WA-Add-type-GL_NONE-to-choose-mesa-format.patch
Labels: PR approved

#1914 Upgrade s master to Android 12L
  aosp_diff/caas/frameworks/base/0004-Add-isVisible-public-API.patch
  aosp_diff/caas/system/sepolicy/0003-Move-mediatranscoding-type-to-public.patch
  aosp_diff/celadon_ivi/frameworks/native/0002-Steering-Wheel-Input-Device-Mapping-with-Primary-Dis.patch
  aosp_diff/celadon_ivi/packages/apps/Car/Settings/0001-Volume-Control-Management-Based-on-Audio-Zone.patch
  aosp_diff/celadon_ivi/packages/services/Car/0003-Multi-Passenger-Feature-Support-in-IVI-AOSP.patch
  aosp_diff/celadon_ivi/packages/services/Car/0005-Fix-EVS-sample-driver-not-getting-started-as-service.patch
  aosp_diff/celadon_ivi/packages/services/Car/0007-Disable-evs-manager-since-it-is-not-needed.patch
  aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/external/minigbm/0001-gralloc4-Remove-gralloc4-build-as-it-is-not-needed.patch
  aosp_diff/preliminary/external/minigbm/0002-Remove-libgbm-creation-twice.patch
  aosp_diff/preliminary/frameworks/av/21_0021-move-MediaCodec-metrics-processing-to-looper-thread.bulletin.patch
  aosp_diff/preliminary/frameworks/base/09_0009-Revert-Increase-debounce-time-for-DISCONNECT-process.patch
  aosp_diff/preliminary/frameworks/base/12_0012-abandon-child-sessions-1-n.patch
  aosp_diff/preliminary/frameworks/base/14_0014-Prevent-apps-from-creating-blocked-channel-groups.patch
  aosp_diff/preliminary/frameworks/base/19_0019-Security-fixes-for-PendingIntent-related-apis-in-Lau.patch
  aosp_diff/preliminary/frameworks/base/23_0023-RESTRICT-AUTOMERGE-Do-not-resume-activity-if-behind-a-tran.patch
  aosp_diff/preliminary/frameworks/base/25_0025-Ongoing-Call-Don-t-call-getIntent-to-avoid-a-security-vul.patch
  aosp_diff/preliminary/frameworks/base/28_0028-Only-allow-trusted-overlays-to-specify-FLAG_SLIPPERY.patch
  aosp_diff/preliminary/frameworks/base/29_0029-Add-ALLOW_SLIPPERY_TOUCHES-permission.patch
  aosp_diff/preliminary/frameworks/base/34_0034-Prevent-exfiltration-of-system-files-via-user-image-settings.patch
  aosp_diff/preliminary/frameworks/base/45_0045-Update-ServiceState-broadcast-for-location-permissions.patch
  aosp_diff/preliminary/frameworks/base/46_0046-DO-NOT-MERGE-WM-Call-Transaction-sanitize.patch
  aosp_diff/preliminary/frameworks/base/47_0047--RESTRICT-AUTOMERGE-Only-allow-system-and-same-app-to-apply-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/48_0048-DO-NOT-MERGE-Suppress-notifications-when-device-enter-lockdo.bulletin.patch
  aosp_diff/preliminary/frameworks/base/52_0052-Remove-package-title-from-notification-access-confirmation-i.bulletin.patch
  aosp_diff/preliminary/frameworks/base/73_0073--DO-NOT-MERGE-Do-not-dismiss-keyguard-after-SIM-PUK-unlock.bulletin.patch
  aosp_diff/preliminary/frameworks/base/90-0090-DO-NOT-MERGE-Update-window-with-FLAG_SECURE-when-bouncer-i.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0109-Do-not-clear-calling-identify-when-using-BiometricPr.patch
  aosp_diff/preliminary/frameworks/base/99_0113-fpService-authWithPrompt-uses-correct-user-handle.patch
  aosp_diff/preliminary/frameworks/base/99_0120-Disable-click-on-privacy-chip-before-provision.patch
  aosp_diff/preliminary/frameworks/base/99_0121-Fix-for-ASB-Feb-2023-Build-issue.patch
  aosp_diff/preliminary/frameworks/base/99_0124-Move-service-initialization.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0125-Enable-user-graularity-for-lockdown-mode.patch
  aosp_diff/preliminary/system/sepolicy/12_0012-Adding-Android-12L-related-api-changes.patch
  bsp_diff/caas/device/intel/mixins/0002-Change-the-path-of-ueventd.rc.patch
  bsp_diff/caas/device/intel/mixins/0003-Adding-API-level-changes-for-ANdroid-12L.patch
  bsp_diff/caas_dev/device/intel/mixins/0001-Change-the-path-of-ueventd.rc.patch
  bsp_diff/caas_dev/device/intel/mixins/0002-Android-12L-related-API-ndk-and-sepolcy-change.patch
  bsp_diff/celadon_ivi/device/intel/mixins/0001-Adding-Android-12L-related-API-changes.patch
  bsp_diff/celadon_ivi/device/intel/mixins/0002-Disable-evs-hal-and-service-as-it-is-crashing-on-12L.patch
  bsp_diff/celadon_ivi/device/intel/mixins/0003-Change-the-path-of-ueventd.rc.patch
  bsp_diff/celadon_ivi/device/intel/project-celadon/celadon_ivi/0001-mixins.spec-changed-for-12L-boot.patch
Labels: Valid commit message, PR approved

#1918 Fix the build error for buildbot
  aosp_diff/caas/system/sepolicy/0003-Move-mediatranscoding-type-to-public.patch
Labels: Valid commit message

#1923 Save app setting of "Peak Performance" to database immediately.
  aosp_diff/celadon_ivi/packages/services/Car/0008-Save-app-setting-of-Peak-Performance-to-database-imm.patch
Labels: Valid commit message, PR approved

#1925 CVE: Update build_weekly.sh with latest commit tag
  host/kernel/lts2020-chromium/build_weekly.sh
Labels: Valid commit message, PR approved

#1934 Reverting the patch to fix black screen issue.
  aosp_diff/celadon_ivi/packages/services/Car/0009-Revert-Force-stop-bootanimation-when-CarLauncher-UI-.patch
Labels: Valid commit message, PR approved

#1935 Fix for Calendar App to Launch in Passenger zone.
  aosp_diff/celadon_ivi/packages/services/Car/0010-Fix-for-Calendar-App-to-Launch-in-Passenger-zone.patch
Labels: Valid commit message, PR approved

#1926 Merge the diff patches to base external/mesa3d project
  bsp_diff/common/hardware/intel/external/mesa3d-intel/0001-INTERNAL-WA-to-disable-virgl-disk-cache-for-VirtIO-b.patch
  bsp_diff/common/hardware/intel/external/mesa3d-intel/0005-vulkan-fix-buf-map-failure-in-32bits-app.patch
  bsp_diff/common/hardware/intel/external/mesa3d-intel/0006-Fix-Android-Swapchain-alignment-issue.patch
  bsp_diff/common/hardware/intel/external/mesa3d-intel/0007-Fix-32bit-mmap-issue.patch
Labels: Valid commit message, PR approved

#1936 Enable meminfo, gfxinfo...etc service by default
  aosp_diff/cic_cloud/frameworks/base/0002-Check-the-property-before-starting-some-services.patch
Labels: PR approved

#1940 Changes for compatibility with nn-hal update
  bsp_diff/common/vendor/intel/external/project-celadon/nn-hal/0001-WA-Disabled-operations-causing-VTS-failures.patch
Labels: Valid commit message, PR approved

#1950 Add null check for intent in KeyguardManager
  aosp_diff/preliminary/frameworks/base/99_0141-Add-null-check-for-intent-in-KeyguardManager.patch
Labels: Valid commit message, PR approved

#1929 add pipe communication to vhal
  bsp_diff/caas/vendor/intel/external/project-celadon/camera-vhal/0007-add-pipe-communication.patch
Labels: Valid commit message, PR approved

#1949 ASB - Security Patch integration July 2023
  aosp_diff/common/build/make/0002-Updating-Platform-Security-version.patch
  aosp_diff/common/external/freetype/0001-DO-NOT-MERGE-Cherry-pick-two-upstream-changes.bulletin.patch
  aosp_diff/common/frameworks/base/0174--RESTRICT-AUTOMERGE-Passpoint-Add-more-check-to-limit-the-c.bulletin.patch
  aosp_diff/common/frameworks/base/0175-Ensure-that-only-SysUI-can-override-pending-intent-launch-fl.bulletin.patch
  aosp_diff/common/frameworks/base/0176-Revert-Ensure-that-only-SysUI-can-override-pending-intent-l.bulletin.patch
  aosp_diff/common/frameworks/base/0177-Add-a-limit-on-channel-group-creation.bulletin.patch
  aosp_diff/common/frameworks/base/0178-Remove-Activity-if-it-enters-PiP-without-window.bulletin.patch
  aosp_diff/common/frameworks/base/0179-Sanitize-VPN-label-to-prevent-HTML-injection.bulletin.patch
  aosp_diff/common/frameworks/base/0180-Import-translations.-DO-NOT-MERGE-ANYWHERE.patch
  aosp_diff/common/frameworks/base/0181-DO-NOT-MERGE-Add-size-check-on-PPS-policy.bulletin.patch
  aosp_diff/common/frameworks/base/0182-DO-NOT-MERGE-Limit-the-ServiceFriendlyNames.bulletin.patch
  aosp_diff/common/frameworks/base/0183-Only-allow-NEW_TASK-flag-when-adjusting-pending-intents.bulletin.patch
  aosp_diff/common/frameworks/base/0184-DO-NOT-MERGE-Dismiss-keyguard-when-simpin-auth-d-and-.bulletin.patch
  aosp_diff/common/frameworks/base/0185-DO-NOT-MERGE-Increase-notification-channel-limit-.bulletin.patch
  aosp_diff/common/frameworks/base/0186-Verify-URI-permissions-for-EXTRA_REMOTE_INPUT_HISTORY_ITEMS-.bulletin.patch
  aosp_diff/common/frameworks/base/0187-Truncate-ShortcutInfo-Id.bulletin.patch
  aosp_diff/common/frameworks/base/0188-Visit-URIs-in-landscape-portrait-custom-remote-views-.bulletin.patch
  aosp_diff/common/frameworks/opt/net/wifi/0003--RESTRICT-AUTOMERGE-Only-handle-saveToStore-from-the-WifiNe.bulletin.patch
  aosp_diff/common/frameworks/opt/net/wifi/0004-DO-NOT-MERGE-Limit-the-number-of-Passpoint-per-App.patch
  aosp_diff/common/system/bt/0028-Fix-gatt_end_operation-buffer-overflow.bulletin.patch
  aosp_diff/common/system/nfc/0006-OOBW-in-rw_i93_send_to_upper.patch
Labels: PR approved

#1946 Fix for Local Media Player in Passenger zone.
  aosp_diff/celadon_ivi/packages/apps/Car/libs/0001-Fix-for-Local-Media-Player-in-Passenger-Zone.patch
  aosp_diff/celadon_ivi/packages/services/Car/0011-Fix-for-Local-Media-Player-in-Passenger-Zone.patch
Labels: Valid commit message, PR approved

#1941 ASB - Security Patch integration July 2023
  aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/external/freetype/0002-DO-NOT-MERGE-Cherry-pick-two-upstream-changes.bulletin.patch
  aosp_diff/preliminary/external/skia/0001-Enforce-program-stack-limits-on-function-parameters-.bulletin.patch
  aosp_diff/preliminary/frameworks/av/0015-audio-policy-fix-sensor-privacy-listener.bulletin.patch
  aosp_diff/preliminary/frameworks/av/0016-Revert-audio-policy-fix-sensor-privacy-listener-.bulletin.patch
  aosp_diff/preliminary/frameworks/av/0017-Force-unsilence-record-clients-on-startInput.bulletin.patch
  aosp_diff/preliminary/frameworks/base/85_0085-Ensure-that-only-SysUI-can-override-pending-intent-launch-fl.bulletin.patch
  aosp_diff/preliminary/frameworks/base/86_0086-Revert-Ensure-that-only-SysUI-can-override-pending-intent-l.bulletin.patch
  aosp_diff/preliminary/frameworks/base/87_0087-Remove-Activity-if-it-enters-PiP-without-window.bulletin.patch
  aosp_diff/preliminary/frameworks/base/88_0088-Sanitize-VPN-label-to-prevent-HTML-injection.bulletin.patch
  aosp_diff/preliminary/frameworks/base/89_0089-Grant-URI-permissions-to-the-CallStyle-related-ones.bulletin.patch
  aosp_diff/preliminary/frameworks/base/90_0090-Only-allow-NEW_TASK-flag-when-adjusting-pending-intents.bulletin.patch
  aosp_diff/preliminary/frameworks/base/91_0091-Dismiss-keyguard-when-simpin-auth-d-and-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/92_0092-Truncate-ShortcutInfo-Id.bulletin.patch
  aosp_diff/preliminary/frameworks/base/93_0093-Watch-uid-proc-state-instead-of-importance-for-1-time-permis.bulletin.patch
  aosp_diff/preliminary/frameworks/base/94_0094-Verify-URI-permissions-for-EXTRA_REMOTE_INPUT_HISTORY_ITEMS-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/95_0095--RESTRICT-AUTOMERGE-Prevent-installing-apps-in-policy-restr.bulletin.patch
  aosp_diff/preliminary/frameworks/base/96_0096-Visit-URIs-in-landscape-portrait-custom-remote-views-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/0016-Refine-permission-check-process-of-2-pane-deep-link.patch
  aosp_diff/preliminary/packages/apps/Settings/0017-Fix-Bluetooth-and-Wifi-scanning-location-MainSwitch-page-po.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0031-Fix-gatt_end_operation-buffer-overflow.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/0008-Add-size-check-on-PPS-policy.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/0009-Limit-the-ServiceFriendlyNames-and-limit-the-number-of-Passp.bulletin.patch
  aosp_diff/preliminary/system/nfc/03_0003-OOBW-in-rw_i93_send_to_upper-.bulletin.patch
Labels: Valid commit message, PR approved

#1908 AVX2 implementation for memmove
  aosp_diff/preliminary/bionic/0006-avx2-implementation-for-memmove-api.patch
Labels: Valid commit message, PR approved
