Repository projectceladon/vendor-intel-utils, pull requests merged in 2023-11, with the labels that each got.

#2182 ftrace: Ignore f2fs/f2fs_truncate_partial_nodes.nid field
  aosp_diff/preliminary/external/perfetto/0001-ftrace-Ignore-f2fs-f2fs_truncate_partial_nodes.nid-f.patch
Labels: Valid commit message, PR approved

#2162 Fix for green overlay during video playback with SG1
  bsp_diff/cic_cloud/vendor/intel/external/project-celadon/minigbm/0007-Fix-for-green-overlay-during-video-playback-with-SG1.patch
Labels: Valid commit message, PR approved

#2189 Remove kernel and wi-fi diff patches
  bsp_diff/common/device/intel/common/0001-Add-kernel-headers-for-use-by-vendor-HAL-libraries.patch
  bsp_diff/common/device/intel/mixins/13_0013-Fix-for-wifi-not-working-due-to-switch-from-hidl-to-.patch
  bsp_diff/common/device/intel/mixins/22_0022-Enable-kernel-configs-for-vendor-interface-compatibi.patch
  bsp_diff/common/device/intel/project-celadon/0002-Add-6.1-kernel-source-and-config-folder-option.patch
  bsp_diff/common/device/intel/project-celadon/0003-caas-Change-default-kernel-to-6.1.patch
Labels: Valid commit message, PR approved

#2168 Remove AIDL Camera Patch
  bsp_diff/common/device/intel/mixins/21_0021-Camera-Add-aidl-camera-provider-for-external-camera.patch
  bsp_diff/common/device/intel/sepolicy/06_0006-Add-ICameraProvider-aidl-hal-service-contexts.patch
Labels: Valid commit message, PR approved

#2186 Fixed for Unnecessary app shortcut icon in MD Launcher.
  aosp_diff/preliminary/packages/services/Car/0017-Fixed-for-Unnecessary-app-shortcut-icon-in-MD-Launch.patch
Labels: Valid commit message, PR approved

#2177 ASB - Security Patch integration November 2023
  aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/av/28_0028-Fix-for-heap-buffer-overflow-issue-flagged-by-fuzzer-test-.bulletin.patch
  aosp_diff/preliminary/frameworks/av/29_0029-Fix-heap-use-after-free-issue-flagged-by-fuzzer-test-.bulletin.patch
  aosp_diff/preliminary/frameworks/av/30_0030-Initialise-VPS-buffer-to-NULL-in-constructor.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0201-Verify-URI-permissions-for-EXTRA_REMOTE_INPUT_HISTOR.patch
  aosp_diff/preliminary/frameworks/base/99_0201-Verify-URI-permissions-for-notification-shortcutIcon.patch
  aosp_diff/preliminary/frameworks/base/99_0213-enforce-stricter-rules-when-registering-phoneAccounts.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0215-Add-userId-check-before-loading-icon-in-Device-Controls.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0216-DO-NOT-MERGE-Fix-BAL-via-notification-publicVersion.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0217--DO-NOT-MERGE-Check-caller-s-uid-in-backupAgentCreated-callback.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0218-Use-type-safe-API-of-readParcelableArray.bulletin.patch
  aosp_diff/preliminary/packages/modules/DnsResolver/0001-Fix-use-after-free-in-DNS64-discovery-thread.bulletin.patch
  aosp_diff/preliminary/packages/modules/StatsD/0001-Make-log-reader-thread-a-class-member.bulletin.patch
  aosp_diff/preliminary/packages/providers/TelephonyProvider/0003-DO-NOT-MERGE-Block-access-to-sms-mms-db-from-work-profile-.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/13_0013-enforce-stricter-rules-when-registering-phoneAccounts.bulletin.patch
  aosp_diff/preliminary/system/ca-certificates/0002-Remove-E-Tugra-certificates-.bulletin.patch
Labels: Valid commit message, PR approved

#2191 Merge Thermal patches directly to UMR0 main repos.
  bsp_diff/common/device/intel/mixins/18_0018-MIXIN-changes-for-AIDL-Conversion-of-Thermal-HAL.patch
  bsp_diff/common/device/intel/sepolicy/05_0005-SELinux-change-for-AIDL-Conversion-of-Thermal-HAL.patch
  bsp_diff/common/vendor/intel/hardware/interfaces/05_0005-AIDL-Conversion-of-Thermal-HAL.patch
Labels: Valid commit message, PR approved

#2165 ASB - Security Patch integration November 2023
  aosp_diff/common/build/make/0002-Updating-Platform-Security-version.patch
  aosp_diff/common/frameworks/av/0021-Fix-for-heap-buffer-overflow-issue-flagged-by-fuzzer-test-.bulletin.patch
  aosp_diff/common/frameworks/av/0022-Fix-heap-use-after-free-issue-flagged-by-fuzzer-test-.bulletin.patch
  aosp_diff/common/frameworks/base/0216-enforce-stricter-rules-when-registering-phoneAccounts.bulletin.patch
  aosp_diff/common/frameworks/base/0218-Add-userId-check-before-loading-icon-in-Device-Contr.patch
  aosp_diff/common/frameworks/base/0219-DO-NOT-MERGE-Fix-BAL-via-notification-publicVersion.bulletin.patch
  aosp_diff/common/frameworks/base/0220--DO-NOT-MERGE-Check-caller-s-uid-in-backupAgentCreated-callback.bulletin.patch
  aosp_diff/common/frameworks/base/0221-Use-type-safe-API-of-readParcelableArray.bulletin.patch
  aosp_diff/common/frameworks/base/0222-RESTRICT-AUTOMERGE-Make-log-reader-thread-a-class-member.bulletin.patch
  aosp_diff/common/packages/modules/DnsResolver/0001-Fix-use-after-free-in-DNS64-discovery-thread.bulletin.patch
  aosp_diff/common/packages/providers/TelephonyProvider/0003-DO-NOT-MERGE-Block-access-to-sms-mms-db-from-work-profile-.bulletin.patch
  aosp_diff/common/packages/services/BuiltInPrintService/0001-Adjust-APIs-for-CUPS-2-3-3.bulletin.patch
  aosp_diff/common/packages/services/Telecomm/0014-enforce-stricter-rules-when-registering-phoneAccounts.bulletin.patch
  aosp_diff/common/system/ca-certificates/0002-Remove-E-Tugra-certificates-.bulletin.patch
Labels: Valid commit message, PR approved

#2156 Remove bootcontrol related diff files
  bsp_diff/common/device/intel/mixins/14_0001-Update-bootcontrol-from-HIDL-to-AIDL.patch
  bsp_diff/common/device/intel/mixins/15_0002-Add-sepolicy-path-for-bootcontrol.patch
  bsp_diff/common/device/intel/sepolicy/03_0001-Add-sepolicy-for-bootcontrol-service.patch
  bsp_diff/common/vendor/intel/hardware/interfaces/03_0001-bootctrl-Update-to-AIDL-implementation.patch
Labels: Valid commit message, PR approved

#2175 merge sensors and wifikeystore patches to UMR0
  bsp_diff/common/device/intel/mixins/17_0002-mixin-changes-to-support-sensors-aidl-hal.patch
  bsp_diff/common/device/intel/mixins/20_0020-Removing-the-deprecated-android.system.wifi.keystore.patch
  bsp_diff/common/device/intel/sepolicy/05_0002-Sepolicy-changes-to-support-sensors-aidl-hal.patch
  bsp_diff/common/vendor/intel/hardware/interfaces/06_0001-google-default-implementation-for-Sensor-aidl.patch
  bsp_diff/common/vendor/intel/hardware/interfaces/06_0002-Sensors-HAL-Update-to-AIDL-implementation.patch
  bsp_diff/common/vendor/intel/hardware/interfaces/06_0003-changing-sensors-aidl-to-version_2-in-manifest.xml-t.patch
  bsp_diff/common/vendor/intel/hardware/interfaces/06_0004-adding-debug-logs-for-AIDL-sensors-HAL.patch
  bsp_diff/common/vendor/intel/hardware/interfaces/07_0001-fixing-DEBUG-variable-value-to-enable-disable-logs.patch
Labels: Valid commit message, PR approved

#2206 Fix javacrash on com.android.gallery3d as CursorIndexOutOfBoundsExcep…
  aosp_diff/preliminary/packages/apps/Gallery2/0003-Fix-javacrash-on-com.android.gallery3d-as-CursorInde.patch
Labels: Valid commit message, PR approved

#2207 Fix javacrash on com.android.gallery3d with null object
  aosp_diff/preliminary/packages/apps/Gallery2/0002-Fix-javaCrash-on-com.android.gallery3d-with-null-obj.patch
Labels: PR approved

#2204 Support OTA from U disk in android normal mode
  aosp_diff/preliminary/bootable/recovery/03_0003-Modify-systemupdatersample-to-support-OTA-from-U-dis.patch
  aosp_diff/preliminary/system/vold/0002-Remove-the-existence-check-of-mkfs.exfat-and-fsck.ex.patch
Labels: Valid commit message, PR approved

#2211 Revert "ftrace: Ignore f2fs/f2fs_truncate_partial_nodes.nid field"
  aosp_diff/celadon_ivi/external/perfetto/0001-ftrace-Ignore-f2fs-f2fs_truncate_partial_nodes.nid-f.patch
Labels: Valid commit message, PR approved

#2215 Renaming Lunch target from caas_dev to caas_vbb
  aosp_diff/caas_vbb/include_preliminary
  bsp_diff/caas_vbb/include_common
Labels: Valid commit message, PR approved

#2219 Create Lunch target from caas_vbt to caas_cvmb
  aosp_diff/caas_cvmb/include_preliminary
  aosp_diff/caas_vbt/include_preliminary
  bsp_diff/caas_cvmb/include_common
  bsp_diff/caas_vbt/include_common
Labels: Valid commit message, PR approved

#2203 Disable thermal daemon excessive logs.
  aosp_diff/preliminary/external/thermal_daemon/0001-Disable-Thermal-Daemon-logs.patch
Labels: Valid commit message, PR approved

#2185 Add 88Q2122 eth phy suspend resume code
  bsp_diff/common/kernel/linux-intel-lts2021/0028-Add-88q2122-eth-phy-suspend-resume-code.patch
Labels: Valid commit message, PR approved

#2224 Change the path of ueventd.rc
  bsp_diff/common/device/intel/mixins/0003-Change-the-path-of-ueventd.rc.patch
Labels: Valid commit message, PR approved

#2197 add feature for virtio gpu driver
  bsp_diff/common/kernel/linux-intel-lts2021/0030-add-scaling-support.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0031-suppport-configurable-queue-number.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0032-enable-vblank-for-crtc.patch
Labels: Invalid commit message, PR approved

#2226 Fixed for JavaCrash in Gallery app.
  aosp_diff/preliminary/packages/apps/Gallery2/0004-Fixed-for-JavaCrash-in-Gallery-app.patch
Labels: Valid commit message, PR approved

#2217 Set 5G band as default for Wifi AP mode
  aosp_diff/preliminary/packages/modules/Wifi/0011-Set-5G-band-as-default-for-Wifi-AP-mode.patch
Labels: Valid commit message, PR approved

#2216 drm/i915: Sysfs interface to get GFX shmem usage
  bsp_diff/common/kernel/linux-intel-lts2021/0028-drm-i915-Sysfs-interface-to-get-GFX-shmem-usage.patch
Labels: PR approved

#2227 ASB - December 2023 Security Patches integration
  aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/av/31_0031-httplive-fix-use-after-free.bulletin.patch
  aosp_diff/preliminary/frameworks/av/32_0032-Correct-attribution-source-for-MMAP-thread.bulletin.patch
  aosp_diff/preliminary/frameworks/av/33_0033-Condition-background-record-restriction-on-Sdk.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0219-On-device-lockdown-always-show-the-keyguard.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0220-Visit-Uris-added-by-WearableExtender.patch
  aosp_diff/preliminary/frameworks/base/99_0221-Fix-bypass-BAL-via-requestGeofence-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0222-Visit-Uris-related-to-Notification-style-extras.patch
  aosp_diff/preliminary/frameworks/base/99_0223-RESTRICT-AUTOMERGE-Drop-invalid-data-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0224-Disable-priority-conversation-widget-for-secondary-users.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0225-Validate-URI-based-shortcut-icon-at-creation-time-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0226-Require-permission-to-unlock-keyguard.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0227-Restrict-number-of-shortcuts-can-be-added-through-addDynamicShor.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0228-Use-readUniqueFileDescriptor-in-incidentd-service.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0229-Validate-userId-when-publishing-shortcuts.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0230-Revert-On-device-lockdown-always-show-the-keyguard-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0231-Updated-always-show-the-keyguard-on-device-lockdown.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0232-Move-startWatchingModeWithFlags-to-the-native-supported-binder-c.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0233-RESTRICT-AUTOMERGE-Check-URI-permissions-for-resumable-media-ar.bulletin.patch
  aosp_diff/preliminary/frameworks/native/19_0019-Add-AppOps-overload-to-be-able-to-watch-foreground-changes-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Bluetooth/05_0005-Fix-UAF-in-CallbackEnv.bulletin.patch
  aosp_diff/preliminary/packages/apps/Launcher3/04_0004-Fix-permission-bypass-in-legacy-shortcut.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/14_0014-Resolve-account-image-icon-profile-boundary-exploit-.bulletin.patch
  aosp_diff/preliminary/system/bt/40_0040-Reorganize-the-code-for-checking-auth-requirement.bulletin.patch
  aosp_diff/preliminary/system/bt/41_0041-Reject-access-to-secure-services-authenticated-from-temp-bonding.bulletin.patch
  aosp_diff/preliminary/system/bt/42_0042-Reject-access-to-secure-service-authenticated-from-a-temp-bondin.bulletin.patch
  aosp_diff/preliminary/system/bt/43_0043-Reject-access-to-secure-service-authenticated-from-a-temp-bondi.bulletin.patch
  aosp_diff/preliminary/system/bt/44_0044-Enforce-authentication-if-encryption-is-required.bulletin.patch
  aosp_diff/preliminary/system/bt/45_0045-Factor-out-duplicate-code-for-parsing-gap-data.bulletin.patch
  aosp_diff/preliminary/system/bt/46_0046-Fix-an-OOB-bug-in-parse_gap_data.bulletin.patch
  aosp_diff/preliminary/system/bt/47_0047-Fix-timing-attack-in-BTM_BleVerifySignature.bulletin.patch
  aosp_diff/preliminary/system/bt/48_0048-Add-bounds-checks-in-btif_avrcp_audio_track-cc.bulletin.patch
  aosp_diff/preliminary/system/netd/0001-Fix-Heap-use-after-free-in-MDnsSdListener-Monitor-run.bulletin.patch
Labels: Valid commit message

#2234 Fix 88Q2122 eth phy remote wakeup disable failed issue
  bsp_diff/common/kernel/linux-intel-lts2021/0033-Fix-88Q2122-eth-phy-remote-wakeup-disable-failed-issue.patch
Labels: Valid commit message, PR approved

#2229 ASB - December 2023 Security Patches integration
  aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/av/0022-httplive-fix-use-after-free.bulletin.patch
  aosp_diff/preliminary/frameworks/av/0023-Condition-background-record-restriction-on-Sdk.bulletin.patch
  aosp_diff/preliminary/frameworks/av/0024-Correct-attribution-source-for-MMAP-thread.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0140-On-device-lockdown-always-show-the-keyguard.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0141-Visit-Uris-added-by-WearableExtender.patch
  aosp_diff/preliminary/frameworks/base/99_0142-Update-AccountManagerService-checkKeyIntentParceledCorrectly-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0143-Fix-bypass-BAL-via-requestGeofence-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0144-Visit-Uris-related-to-Notification-style-extras.patch
  aosp_diff/preliminary/frameworks/base/99_0145-RESTRICT-AUTOMERGE-Drop-invalid-data-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0146-Validate-URI-based-shortcut-icon-at-creation-time-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0147-Disable-priority-conversation-widget-for-secondary-u.patch
  aosp_diff/preliminary/frameworks/base/99_0148-Require-permission-to-unlock-keyguard.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0149-Restrict-number-of-shortcuts-can-be-added-through-addDynamicShor.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0150-Use-readUniqueFileDescriptor-in-incidentd-service.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0151-Validate-userId-when-publishing-shortcuts.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0152-Revert-On-device-lockdown-always-show-the-keyguard-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0153-Updated-always-show-the-keyguard-on-device-lockdown.patch
  aosp_diff/preliminary/frameworks/base/99_0154-Move-startWatchingModeWithFlags-to-the-native-supported-binder-c.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0155-Stop-using-deprecated-getParcelable-method-in-AccountManagerServ.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0156-Check-URI-permissions-for-resumable-media-artwork.patch
  aosp_diff/preliminary/frameworks/native/09_0009-Add-AppOps-overload-to-be-able-to-watch-foreground-changes-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Launcher3/0003-Fix-permission-bypass-in-legacy-shortcut.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0038-Fix-multiple-OOB-bugs-in-btm_ble_gap-cc.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0039-Reject-access-to-secure-service-authenticated-from-a-temp-bondin.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0040-Reject-access-to-secure-service-authenticated-from-a-temp-bondi.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0041-Reorganize-the-code-for-checking-auth-requirement.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0042-Enforce-authentication-if-encryption-is-required.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0043-Reject-access-to-secure-services-authenticated-from-temp-bonding.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0044-Factor-out-duplicate-code-for-parsing-gap-data.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0045-Fix-an-OOB-bug-in-parse_gap_data.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0046-Add-bounds-checks-in-btif_avrcp_audio_track-cc.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0047-Fix-UAF-in-CallbackEnv.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0048-Fix-timing-attack-in-BTM_BleVerifySignature.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/0012-Resolve-account-image-icon-profile-boundary-exploit-.bulletin.patch
  aosp_diff/preliminary/system/netd/0001-Fix-Heap-use-after-free-in-MDnsSdListener-Monitor-run.bulletin.patch
Labels: Valid commit message, PR approved
