Repository projectceladon/vendor-intel-utils, pull requests merged in 2023-09, with the labels that each got.

#2062 ASB - Security Patch integration September 2023
  aosp_diff/common/build/make/0002-Updating-Platform-Security-version.patch
  aosp_diff/common/frameworks/av/0020-Fix-Segv-on-unknown-address-error-flagged-by-fuzzer-test-.bulletin.patch
  aosp_diff/common/frameworks/base/0197-Ignore-virtual-presentation-windows-RESTRICT-AUTOMERGE.bulletin.patch
  aosp_diff/common/frameworks/base/0198-Forbid-granting-access-to-NLSes-with-too-long-component-name.bulletin.patch
  aosp_diff/common/frameworks/base/0199-Update-AccountManagerService-checkKeyIntentParceledCorrectly.bulletin.patch
  aosp_diff/common/frameworks/base/0200-Improve-user-handling-when-querying-for-resumable-me.patch
  aosp_diff/common/frameworks/native/0020-Allow-sensors-list-to-be-empty.bulletin.patch
  aosp_diff/common/packages/apps/Launcher3/0002-Fix-permission-issue-in-legacy-shortcut.bulletin.patch
  aosp_diff/common/packages/apps/Nfc/0004-Ensure-that-SecureNFC-setting-cannot-be-bypassed.bulletin.patch
  aosp_diff/common/packages/apps/Settings/0032-DO-NOT-MERGE-Don-t-hide-approved-NLSes-in-Settings.bulletin.patch
  aosp_diff/common/packages/apps/Settings/0033-Settings-don-t-try-to-allow-NLSes-with-too-long-component-n.bulletin.patch
  aosp_diff/common/packages/apps/Settings/0034-DO-NOT-MERGE-Prevent-non-system-IME-from-becoming-device-ad.bulletin.patch
  aosp_diff/common/packages/providers/MediaProvider/0006-Remove-invalid-surrogates-during-bindSelection.bulletin.patch
  aosp_diff/common/packages/providers/MediaProvider/0007-Canonicalize-file-path-for-insertion-by-legacy-apps.bulletin.patch
  aosp_diff/common/packages/services/Telephony/0002-RESTRICT-AUTOMERGE-Fixed-leak-of-cross-user-data-in-multiple.bulletin.patch
  aosp_diff/common/system/bt/0029-Fix-an-integer-overflow-bug-in-avdt_msg_asmbl.bulletin.patch
  aosp_diff/common/system/bt/0030-Fix-integer-overflow-in-build_read_multi_rsp.bulletin.patch
  aosp_diff/common/system/bt/0031-Fix-potential-abort-in-btu_av_act-cc.bulletin.patch
  aosp_diff/common/system/bt/0032-Fix-UAF-in-gatt_cl-cc.bulletin.patch
Labels: PR approved

#2064 Fix random crash on Ximalaya app.
  aosp_diff/celadon_ivi/frameworks/base/0003-Fix-random-crash-on-Ximalaya-app.patch
Labels: Valid commit message, PR approved

#2066 Add support for Marvell 88q2122 phy driver
  bsp_diff/common/kernel/linux-intel-lts2021/0023-Add-support-for-Marvell-88q2122-phy-driver.patch
Labels: Valid commit message

#2069 [WA] Add a patch which remove some code to fix a reboot bug
  aosp_diff/celadon_ivi/system/core/0001-WA-remove-some-code-to-fix-a-reboot-bug.patch
Labels: Valid commit message, PR approved

#2090 Remove diff patch setting sepolicy to permissive
  aosp_diff/preliminary/system/core/0001-Set-selinux-to-permissive-mode-in-user-build.patch
Labels: Valid commit message, PR approved

#2067 Fix issues of optee keymaster
  aosp_diff/celadon_ivi/vendor/intel/optee/optee_apps/0001-Fix-issues-of-optee-keymaster.patch
Labels: Valid commit message, PR approved

#2088 [WA] Add a revert patch to fix a perfetto issue
  bsp_diff/common/kernel/linux-intel-lts2021/0001-WA-Revert-f2fs-Fix-f2fs_truncate_partial_nodes-ftrac.patch
Labels: Valid commit message

#2101 Fix for Pointer location in Developer options.
  aosp_diff/preliminary/frameworks/base/99_0197-Fix-for-Pointer-location-in-Developer-options.patch
Labels: Valid commit message, PR approved

#2100 Fix a reboot issue
  aosp_diff/preliminary/system/core/0001-WA-remove-some-code-to-fix-a-reboot-bug.patch
Labels: Valid commit message, PR approved

#2053 ftrace: Ignore f2fs/f2fs_truncate_partial_nodes.nid field
  aosp_diff/celadon_ivi/external/perfetto/0001-ftrace-Ignore-f2fs-f2fs_truncate_partial_nodes.nid-f.patch
Labels: Valid commit message, PR approved

#2104 Migrate optee_app patches to common/preliminary folder
  aosp_diff/preliminary/vendor/intel/optee/optee_apps/0001-Fix-issues-of-optee-keymaster.patch
Labels: Valid commit message, PR approved

#2102 Fix patch conflict for docker option
  bsp_diff/common/device/intel/project-celadon/celadon_ivi/0001-mixins.spec-changed-for-12L-boot.patch
Labels: Valid commit message, PR approved

#2073 add telemetry for pci device state
  bsp_diff/common/kernel/linux-intel-lts2021/0026-add-telemetry-for-pci-device-state.patch
Labels: Valid commit message

#2107 Add license file for kernel diff patches
  bsp_diff/celadon_ivi/kernel/LICENSE
  bsp_diff/common/kernel/LICENSE
Labels: Valid commit message, PR approved

#2108 Fix Automotive Ethernet can not boot up success
  bsp_diff/common/kernel/linux-intel-lts2021/0025-Fix-Automotive-Ethernet-can-not-boot-up-success.patch
Labels: PR approved

#2110 License file updation
  LICENSE
  LICENSE_for_autopatch
  aosp_diff/LICENSE
  bsp_diff/LICENSE
Labels: Valid commit message, PR approved
