Repository projectceladon/vendor-intel-utils, pull requests merged in 2024-10, with the labels that each got.

#2648 Trigger RNR during reconnect and BT power cycle
  aosp_diff/preliminary/packages/modules/Bluetooth/0012-Trigger-RNR-during-reconnect-and-BT-power-cycle.patch
Labels: Valid commit message, PR approved, Pending Developer Approval, Engineering Build Successful

#2643 ASB-OCT 2024 Security Patches integration
  aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/base_aaos/frameworks/base/99_0295-Fail-parseUri-if-end-is-missing.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0296-Update-AccountManagerService-checkKeyIntent-.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0297-Prevent-Sharing-when-FRP-enforcement-is-in-effect.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0298-RESTRICT-AUTOMERGE-Check-whether-installerPackageName-contains.bulletin.patch
  aosp_diff/base_aaos/libcore/02_0002-Do-not-accept-zip-files-with-invalid-headers-.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Settings/42_0042-RESTRICT-AUTOMERGE-FRP-bypass-defense-in-App-battery-usage-page.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2637 ASB-OCT 2024 Security Patches integration
  aosp_diff/preliminary/build/make/0009-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/base/70_0070-Fail-parseUri-if-end-is-missing.bulletin.patch
  aosp_diff/preliminary/frameworks/base/71_0071-Update-AccountManagerService-checkKeyIntent-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/72_0072-Check-whether-installerPackageName-contains-only-valid-character.bulletin.patch
  aosp_diff/preliminary/libcore/02_0002-Do-not-accept-zip-files-with-invalid-headers-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/17_0017-RESTRICT-AUTOMERGE-FRP-bypass-defense-in-App-battery-usage-page.bulletin.patch
  aosp_diff/preliminary/packages/modules/IntentResolver/01_0001-Prevent-Sharing-when-FRP-enforcement-is-in-effect.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/01_0001-Add-plaintext-WifiConfig-SSID-length-check.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2641 ASB-OCT 2024 Security Patches integration
  aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/base/99_0211-Fail-parseUri-if-end-is-missing.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0212-Update-AccountManagerService-checkKeyIntent-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0213-Prevent-Sharing-when-FRP-enforcement-is-in-effect.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0214--RESTRICT-AUTOMERGE-Check-whether-installerPackageName-contains.bulletin.patch
  aosp_diff/preliminary/libcore/02_0002-Do-not-accept-zip-files-with-invalid-headers-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/0031-RESTRICT-AUTOMERGE-FRP-bypass-defense-in-App-battery-usage-page.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2636 ASB-OCT 2024 Security Patches integration
  aosp_diff/preliminary/build/make/0009-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/base/69_0069-Fail-parseUri-if-end-is-missing.bulletin.patch
  aosp_diff/preliminary/frameworks/base/70_0070-Update-AccountManagerService-checkKeyIntent-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/71_0071-Check-whether-installerPackageName-contains-only-valid-character.bulletin.patch
  aosp_diff/preliminary/libcore/02_0002-Do-not-accept-zip-files-with-invalid-headers-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/17_0017-RESTRICT-AUTOMERGE-FRP-bypass-defense-in-App-battery-usage-page.bulletin.patch
  aosp_diff/preliminary/packages/modules/IntentResolver/01_0001-Prevent-Sharing-when-FRP-enforcement-is-in-effect.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/01_0001-Add-plaintext-WifiConfig-SSID-length-check.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful, Integration Approved

#2642 ASB-OCT 2024 Security Patches integration
  aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/base/99_0281-Fail-parseUri-if-end-is-missing.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0282-Update-AccountManagerService-checkKeyIntent-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0283-Prevent-Sharing-when-FRP-enforcement-is-in-effect.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0284-RESTRICT-AUTOMERGE-Check-whether-installerPackageName-contains.bulletin.patch
  aosp_diff/preliminary/libcore/02_0002-Do-not-accept-zip-files-with-invalid-headers-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/42_0042-RESTRICT-AUTOMERGE-FRP-bypass-defense-in-App-battery-usage-page.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2639 ASB-OCT 2024 Security Patches integration
  aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/base_aaos/frameworks/base/99_0291-Fail-parseUri-if-end-is-missing.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0292-Update-AccountManagerService-checkKeyIntent-.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0293-Prevent-Sharing-when-FRP-enforcement-is-in-effect.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0294-RESTRICT-AUTOMERGE-Check-whether-installerPackageName-contains.bulletin.patch
  aosp_diff/base_aaos/libcore/02_0002-Do-not-accept-zip-files-with-invalid-headers-.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Settings/42_0042-RESTRICT-AUTOMERGE-FRP-bypass-defense-in-App-battery-usage-page.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2654 Fix static analysis issues for thermal daemon for IVI
  aosp_diff/aaos_iasw/external/thermal_daemon/0001-Coverity-fixes-for-Thermal-Daemon.patch
  aosp_diff/aaos_iasw/external/thermal_daemon/0002-Fix-static-analysis-issues-for-thermal-daemon-for-IV.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2650 Kernel v6.1 diff cleanup
  bsp_diff/common/kernel/lts2022-chromium/0001-make-vmmouse-report-relative-values.patch
  bsp_diff/common/kernel/lts2022-chromium/0002-uvc-Add-UVC-GET_DEF-probe-quirk-for-C922-camera.patch
  bsp_diff/common/kernel/lts2022-chromium/0003-Bluetooth-btusb-Add-reset-on-close-quirk-for-Intel-a.patch
  bsp_diff/common/kernel/lts2022-chromium/0004-iwlwifi-Get-driver-and-firmware-version-vendor-comma.patch
  bsp_diff/common/kernel/lts2022-chromium/0007-Fix-compilation-issues-for-fuse-bpf.patch
  bsp_diff/common/kernel/lts2022-chromium/0007-drm-i915-Sysfs-interface-to-get-GFX-shmem-usage.patch
  bsp_diff/common/kernel/lts2022-chromium/0008-ACPI-PM-Propagate-power-button-event-to-user-space-w.patch
  bsp_diff/common/kernel/lts2022-chromium/0009-Enable-sco-driver-for-AX211.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2657 Fixed for SystemUI crash in Passenger Display.
  aosp_diff/base_aaos/packages/apps/Car/SystemUI/0001-Fixed-for-SystemUI-crash-in-Passenger-Display.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2658 Removed patches from bsp_diff for base_aaos.
  bsp_diff/base_aaos/device/intel/mixins/groups/device-specific/base_aaos/0001-WA-Disabled-sepolicy-and-vndk-in-A15.patch
  bsp_diff/base_aaos/device/intel/mixins/groups/device-specific/base_aaos/0002-WA-Disabled-wi-fi-display-service.patch
  bsp_diff/base_aaos/device/intel/mixins/groups/device-specific/base_aaos/0003-Update-composer-aidl-version-to-3.patch
  bsp_diff/base_aaos/device/intel/mixins/groups/device-specific/base_aaos/0003-Updated-compatibility-and-device-matrix-for-some-of.patch
  bsp_diff/base_aaos/device/intel/mixins/groups/device-specific/base_aaos/0004-Removed-Render-script-and-graphics-mapper-hidl.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2652 Cleanup bsp_diff changes.
  bsp_diff/common/device/intel/sepolicy/0001-Add-graphics-related-sepolicy-for-hal_sensors_defaul.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2638 Add special flag for display
  aosp_diff/aaos_iasw/frameworks/native/0001-Add-special-flag-for-display-consumer.patch
  aosp_diff/base_aaos/frameworks/native/0001-Add-special-flag-for-display-consumer.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2659 Revert "Do firmware update of graphics and wifi inside ubu_update_fw"
  bsp_diff/common/device/intel/common/0002-Do-firmware-update-of-graphics-and-wifi-inside-ubu_u.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2666 BSP diff cleanup
  bsp_diff/common/vendor/linux/firmware/0001-Add-SOF-firmware-and-topology-files.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2664 Removing OTA Update patch from bsp_diff
  bsp_diff/common/device/intel/sepolicy/0002-fix-for-OTA-update-through-script-failure.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2667 Cleanup bsp_diff changes for DLKM partition
  bsp_diff/base_aaos/device/intel/mixins/0003-Add-test-kernel-module-for-system-and-odm-DLKM-parti.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2662 [WA]Fix error on joystick operation
  aosp_diff/aaos_iasw/frameworks/native/0001-WA-Fix-error-on-joystick-operation.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2660 Remove camerahal sepolicy patches
  bsp_diff/aaos_iasw/device/intel/sepolicy/0002-Add-iacamera-hal-sepolicy.patch
  bsp_diff/aaos_iasw/device/intel/sepolicy/0003-Change-iacamera-provider-name-in-sepolicy.patch
  bsp_diff/base_aaos/device/intel/sepolicy/0002-Add-iacamera-hal-sepolicy.patch
  bsp_diff/base_aaos/device/intel/sepolicy/0003-Change-iacamera-provider-name-in-sepolicy.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2663 Removing Bsp Diffs for vendor-intel-utils
  bsp_diff/aaos_iasw/vendor/intel/hardware/interfaces/0001-Add-BT-HFP-support-for-TyP2.patch
  bsp_diff/base_aaos/vendor/intel/hardware/interfaces/0001-Add-BT-HFP-support-for-TyP2.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2668 Bsp_diff cleanup.
  bsp_diff/common/vendor/intel/mediasdk_omx_il/01_0001-Add-Android-14-related-build-flags.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2669 Fix error of setting new action bar in Gallery app.
  aosp_diff/aaos_iasw/packages/apps/Gallery2/0002-Fix-error-of-setting-new-action-bar-in-Gallery-app.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2670 Remove SOF License
  bsp_diff/common/vendor/linux/firmware/LICENCE.Intel
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2629 Remove WA patch
  bsp_diff/base_aaos/device/intel/build/0001-WA-Fixed-to-publish-kf4sbl-binary.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2672 Move embargoed targets to embargoed branch
  aosp_diff/aaos_iasw/build/soong/0001-solve-pahole-is-not-allowed-to-be-used-in-build-issu.patch
  aosp_diff/aaos_iasw/frameworks/base/99_0258-Enable-AX210-and-AX201-Bluetooth-for-Android-Automot.patch
  aosp_diff/aaos_iasw/hardware/interfaces/0001-Update-default-KeyMint-version-to-3.patch
  aosp_diff/aaos_iasw/include_preliminary
  aosp_diff/aaos_iasw/packages/apps/Browser2/0001-Fix-crashes-in-Webview-Browser-during-MonkeyTest.patch
  aosp_diff/aaos_iasw/packages/modules/Bluetooth/0001-Disabling-WBS-in-the-BT-stack.patch
  aosp_diff/aaos_iasw/packages/providers/MediaProvider/0001-Reduce-POLL_INTERVAL_MS-to-50ms-to-optimize-cold-boo.patch
  aosp_diff/aaos_iasw/packages/services/BuiltInPrintService/0001-Skip-print-job-if-print-feature-is-not-defined.patch
  aosp_diff/aaos_iasw/packages/services/Car/0001-Enable-HID-and-OPP-profiles-for-aaos.patch
  aosp_diff/aaos_iasw/packages/services/Car/0002-enable-virtio-camera-based-evs-app-for-A15.patch
  aosp_diff/aaos_iasw/packages/services/Telephony/0001-Fix-java-crash-when-Bluetooth-MAP-profile-connects.patch
  autopatch.sh
  bsp_diff/aaos_iasw/device/intel/mixins/0001-adding-required-sensors-xml-files-for-automotive.patch
  bsp_diff/aaos_iasw/device/intel/sepolicy/0002-Add-iacamera-hal-sepolicy.patch
  bsp_diff/aaos_iasw/device/intel/sepolicy/0003-Change-iacamera-provider-name-in-sepolicy.patch
  bsp_diff/aaos_iasw/device/intel/sepolicy/0004-sepolicy-for-running-evs-app.patch
  bsp_diff/aaos_iasw/device/intel/sepolicy/0005-adding-missing-sepolicy-for-evs-app.patch
  bsp_diff/aaos_iasw/hardware/intel/kernelflinger/0053-fix-Build-Error-in-kernelflinger.patch
  bsp_diff/aaos_iasw/vendor/intel/hardware/interfaces/0001-Add-BT-HFP-support-for-TyP2.patch
  bsp_diff/aaos_iasw/vendor/intel/hardware/interfaces/0001-WR-start-surround-view-camera-only-for-reverse-gear.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2674 Move embargoed target to embargoed branch
  aosp_diff/base_aaos/build/make/0001-Fix-for-missing-vendor-lib-modules-folder.patch
  aosp_diff/base_aaos/build/soong/0001-solve-pahole-is-not-allowed-to-be-used-in-build-issu.patch
  aosp_diff/base_aaos/frameworks/base/0001-Enable-BT-for-ivi.patch
  aosp_diff/base_aaos/hardware/interfaces/0001-Update-default-KeyMint-version-to-3.patch
  aosp_diff/base_aaos/hardware/interfaces/0002-Allow-modification-of-Vehicle-HAL-properties.patch
  aosp_diff/base_aaos/include_preliminary
  aosp_diff/base_aaos/packages/apps/Car/SystemUI/0001-Fixed-for-SystemUI-crash-in-Passenger-Display.patch
  aosp_diff/base_aaos/packages/services/Car/0001-Enable-HID-and-OPP-profiles-for-aaos.patch
  aosp_diff/base_aaos/packages/services/Car/0002-Modify-evs-HAL-API-version-to-2.patch
  aosp_diff/base_aaos/packages/services/Car/0002-enable-virtio-camera-based-evs-app-for-A15.patch
  aosp_diff/base_aaos/packages/services/Telephony/0001-Fix-java-crash-when-Bluetooth-MAP-profile-connects.patch
  bsp_diff/aaos_iasw/include_common
  bsp_diff/base_aaos/device/intel/mixins/0001-adding-required-sensors-xml-files-for-automotive.patch
  bsp_diff/base_aaos/device/intel/mixins/0002-adding-required-uncalibrated-sensors-xml-files-for-a.patch
  bsp_diff/base_aaos/device/intel/project-celadon/base_aaos/0002-Fixed-graphics-allocator-hal-issue.patch
  bsp_diff/base_aaos/device/intel/sepolicy/0002-Add-iacamera-hal-sepolicy.patch
  bsp_diff/base_aaos/device/intel/sepolicy/0003-Change-iacamera-provider-name-in-sepolicy.patch
  bsp_diff/base_aaos/device/intel/sepolicy/0005-adding-missing-sepolicy-for-evs-app.patch
  bsp_diff/base_aaos/hardware/intel/kernelflinger/0053-fix-Build-Error-in-kernelflinger.patch
  bsp_diff/base_aaos/hardware/intel/kernelflinger/0055-WA-Fixed-build-error-in-kernelflinger.patch
  bsp_diff/base_aaos/include_common
  bsp_diff/base_aaos/vendor/intel/hardware/interfaces/0001-WR-start-surround-view-camera-only-for-reverse-gear.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2673 Update patch 0003-Enable-wifi-RTT-and-NAN-features.patch.
  bsp_diff/caas/device/intel/mixins/0003-Enable-wifi-RTT-and-NAN-features.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2680 Remove BT HAL bsp_diff patches
  bsp_diff/common/vendor/intel/hardware/interfaces/0004-Remove-bluetooth-hidl-hal.patch
  bsp_diff/common/vendor/intel/hardware/interfaces/0005-Add-aosp-bluetooth-aidl-base-code.patch
  bsp_diff/common/vendor/intel/hardware/interfaces/0006-Modify-BT-aidl-hal-for-bluetooth-bring-up.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2677 Enable capture capabilities
  aosp_diff/preliminary/frameworks/base/73_0073-Enable-capture-capapbilities.patch
  aosp_diff/preliminary/packages/services/Car/0001-Enable-capture-capapbilities.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2679 Move media_c2 aidl diffs to respective git projects
  bsp_diff/common/device/intel/sepolicy/0003-Updated-media-c2-hal-from-hidl-to-aidl.patch
  bsp_diff/common/vendor/intel/external/mediasdk_opensource/0001-Updated-Flags-to-fix-build-error.patch
  bsp_diff/common/vendor/intel/external/onevpl-intel-gpu/0001-Fixed-build-error-in-A15.patch
  bsp_diff/common/vendor/intel/mediasdk_c2/0001-Fixed-build-error-in-mediasdk_c2-component.patch
  bsp_diff/common/vendor/intel/mediasdk_c2/0002-Updated-media-c2-hal-from-hidl-to-aidl.patch
  bsp_diff/common/vendor/intel/mediasdk_c2/0003-Fixed-gralloc4-regression-on-Android-U.patch
  bsp_diff/common/vendor/intel/mediasdk_c2/0004-Add-support-for-mapper5.patch
Labels: Valid commit message, PR approved, Pending Developer Approval, Engineering Build Not Started

#2689 Add comment explaining the use of include_** files.
  aosp_diff/caas/include_preliminary
  bsp_diff/caas/include_common
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2686 Revert "[WA]Fix error on joystick operation"
  aosp_diff/aaos_iasw/frameworks/native/0001-WA-Fix-error-on-joystick-operation.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful, Pending Integration Approval
