Repository projectceladon/vendor-intel-utils, pull requests merged in 2024-07, with the labels that each got.

#2500 Fix crash in Webview Browser during MonkeyTest
  aosp_diff/base_aaos/packages/apps/Browser2/0001-Fix-crash-in-Webview-Browser-during-MonkeyTest.patch
Labels: Invalid commit message, PR approved, Developer Approved, Engineering Build Successful

#2517 adding required uncalibrated sensors xml files for automotive
  bsp_diff/base_aaos/device/intel/mixins/0002-adding-required-uncalibrated-sensors-xml-files-for-a.patch
Labels: Valid commit message, PR approved, Developer Approved

#2519 ASB-July 2024 Security Patches integration
  aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/base_aaos/frameworks/base/99_0281-DO-NOT-MERGE-CDM-Fix-a-security-issue-that-allow-3p-apps-to-s.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0282-RESTRICT-AUTOMERGE-PM-Send-ACTION_PACKAGE_CHANGED-when-mimeGr.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0283-Fix-security-vulnerability-allowing-apps-to-start-from-backgroun.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0284-DO-NOT-MERGE-CDM-Fix-setSkipPrompt-on-Android-S.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0285-Verify-UID-of-incoming-Zygote-connections-.bulletin.patch
  aosp_diff/base_aaos/packages/modules/StatsD/0003-statsd-Make-executor-thread-a-class-member-of-MultiConditionTr.bulletin.patch
  aosp_diff/base_aaos/packages/providers/MediaProvider/09_0009-Prevent-insertion-in-other-users-storage-volumes.bulletin.patch
  aosp_diff/base_aaos/system/bt/62_0062-Fix-an-authentication-bypass-bug-in-SMP.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2513 ASB-July 2024 Security Patches integration
  aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/base_aaos/frameworks/base/99_0277-DO-NOT-MERGE-CDM-Fix-a-security-issue-that-allow-3p-apps-to-s.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0278-RESTRICT-AUTOMERGE-PM-Send-ACTION_PACKAGE_CHANGED-when-mimeGr.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0279-Fix-security-vulnerability-allowing-apps-to-start-from-backgroun.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0280-DO-NOT-MERGE-CDM-Fix-setSkipPrompt-on-Android-S.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0281-Verify-UID-of-incoming-Zygote-connections-.bulletin.patch
  aosp_diff/base_aaos/packages/modules/StatsD/0004-statsd-Make-executor-thread-a-class-member-of-MultiConditionTr.bulletin.patch
  aosp_diff/base_aaos/packages/providers/MediaProvider/09_0009-Prevent-insertion-in-other-users-storage-volumes.bulletin.patch
  aosp_diff/base_aaos/system/bt/58_0058-Fix-an-authentication-bypass-bug-in-SMP.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2512 ASB-July 2024 Security Patches integration
  aosp_diff/preliminary/build/make/0009-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/base/54_0054-PM-Send-ACTION_PACKAGE_CHANGED-when-mimeGroups-are-changed.bulletin.patch
  aosp_diff/preliminary/frameworks/base/55_0055-Fix-security-vulnerability-allowing-apps-to-start-from-backgroun.bulletin.patch
  aosp_diff/preliminary/frameworks/base/56_0056-Verify-UID-of-incoming-Zygote-connections-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/13_0013-RESTRICT-AUTOMERGE-Restrict-WifiDppConfiguratorActivity.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0010-Fix-an-authentication-bypass-bug-in-SMP.bulletin.patch
  aosp_diff/preliminary/packages/modules/StatsD/0002-statsd-Make-executor-thread-a-class-member-of-MultiConditionTr.bulletin.patch
  aosp_diff/preliminary/packages/providers/MediaProvider/0001-Prevent-insertion-in-other-users-storage-volumes.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2506 Kernel rebase to 5.15.149
  bsp_diff/base_aaos/kernel/linux-intel-lts2021/0035-f2fs-explicitly-null-terminate-the-xattr-list.patch
  bsp_diff/base_aaos/kernel/linux-intel-lts2021/0036-binder-fix-use-after-free-in-shinkers-callback.patch
  bsp_diff/base_aaos/kernel/linux-intel-lts2021/0037-f2fs-fix-to-avoid-dirent-corruption.patch
  bsp_diff/base_aaos/kernel/linux-intel-lts2021/0038-block-add-check-that-partition-length-needs-to-be-aligned-with-blocksize.patch
  bsp_diff/base_aaos/kernel/linux-intel-lts2021/0039-efivarfs-force-RO-when-remounting-if-SetVariable-is-not-supported.patch
  bsp_diff/base_aaos/kernel/linux-intel-lts2021/0040-perf-Fix-perf_event_validate_size.patch
  bsp_diff/base_aaos/kernel/linux-intel-lts2021/0041-bpf-Reject-variable-offset-alu-on-PTR_TO_FLOW_KEYS.patch
  bsp_diff/base_aaos/kernel/linux-intel-lts2021/0042-bpf-Fix-re-attachment-branch-in-bpf_tracing_prog_attach.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2510 ASB-July 2024 Security Patches integration
  aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/base/99_0197-PM-Send-ACTION_PACKAGE_CHANGED-when-mimeGroups-are-changed.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0198-Fix-security-vulnerability-allowing-apps-to-start-from-backgroun.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0199-Verify-UID-of-incoming-Zygote-connections-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/0026-Restrict-WifiDppConfiguratorActivity.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0057-Fix-an-authentication-bypass-bug-in-SMP.bulletin.patch
  aosp_diff/preliminary/packages/modules/StatsD/0003-statsd-Make-executor-thread-a-class-member-of-MultiConditionTr.bulletin.patch
  aosp_diff/preliminary/packages/providers/MediaProvider/0007-Prevent-insertion-in-other-users-storage-volumes.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2524 Add patch which modifies evs HAL API version to 2
  aosp_diff/base_aaos/packages/services/Car/0002-Modify-evs-HAL-API-version-to-2.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2526 Add graphics related sepolicy for hal_sensors_default
  bsp_diff/common/device/intel/sepolicy/0001-Add-graphics-related-sepolicy-for-hal_sensors_defaul.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2523 Dynamically disable audio codes
  aosp_diff/preliminary/frameworks/av/0007-Dynamically-disable-audio-codes.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2528 Fix Out-of-bounds access and 32-bit time_t
  bsp_diff/base_aaos/hardware/intel/kernelflinger/0058-Fix-Out-of-bounds-access-and-32-bit-time_t.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2527 Fix Resource leaks, 32-bit time_t usage and uninitialized pointer reads
  bsp_diff/base_aaos/hardware/intel/kernelflinger/0056-Fix-Resource-leaks-and-Uninitialized-pointer-reads.patch
  bsp_diff/base_aaos/hardware/intel/kernelflinger/0057-Fix-Resource-leaks-and-32-bit-time_t-usage.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2532 Remove the data violators for hal_graphics_composer
  bsp_diff/common/device/intel/sepolicy/06_0001-Add-sepolicy-for-composer3-AIDL-HAL-service.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2536 Remove car ui related sepolicy rules from diff
  bsp_diff/aaos_iasw/device/intel/sepolicy/0001-Adding-car-UI-lunch-target.patch
  bsp_diff/base_aaos/device/intel/sepolicy/0001-Adding-car-UI-lunch-target.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2533 Avoid HIGH_ACCURACY request from stationary throttling
  aosp_diff/preliminary/frameworks/base/99_0200-Avoid-HIGH_ACCURACY-request-from-stationary-throttli.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2534 Avoid HIGH_ACCURACY request from stationary throttling
  aosp_diff/preliminary/frameworks/base/57_0057-Avoid-HIGH_ACCURACY-request-from-stationary-throttli.patch
  aosp_diff/preliminary/frameworks/base/58_0058-Apply-pending-transactions-always.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2522 [WA] Fixed for Soft Keyboard Color & key size.
  aosp_diff/base_aaos/packages/apps/Car/LatinIME/0001-WA-Fixed-for-Soft-Keyboard-Color-key-size.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2542 Fix android boot issue in SRIOV mode
  bsp_diff/caas/hardware/intel/external/minigbm-intel/0001-Fix-android-boot-issue-in-SRIOV-mode.patch
  bsp_diff/caas/kernel/linux-intel-lts2022/0001-Revert-Fix-CtsDeqpTestCases-test-failures.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2547 Fix android as SRIOV boot issue
  host/qemu/0013-dm-virtio-gpu-Add-virtio-gpu-plane-format-modifier-s.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2538 migrate to py3
  aosp_diff/preliminary/build/make/0004-Remove-usage-of-F-string.patch
  aosp_diff/preliminary/build/tools/01_0001-Remove-usage-of-F-string.patch
  aosp_diff/preliminary/build/tools/03_0003-WA-Fixed-Build-Error-Releasetools.patch
  aosp_diff/preliminary/external/angle/0001-Build-external-angle-by-python3.patch
  aosp_diff/preliminary/prebuilts/build-tools/01_0001-WA-Fixed-Build-Error-For-Python.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful
