Repository projectceladon/vendor-intel-utils, pull requests merged in 2024-11, with the labels that each got.

#2690 Port required Utils bionic patches to Android-15
  aosp_diff/preliminary/bionic/0003-Optimize-bionic-memory-functions-with-avx2-instructi.patch
  aosp_diff/preliminary/bionic/0004-Optimize-bionic-string-functions-with-avx-implementa.patch
  aosp_diff/preliminary/bionic/0005-avx2-implementation-for-memmove-api.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2698 Fixed for crash in QuickSearchBox.
  aosp_diff/preliminary/packages/apps/QuickSearchBox/0001-Fixed-for-crash-in-QuickSearchBox.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2656 Port required art patches to Android-15
  aosp_diff/preliminary/art/0001-Auto-Fast-JNI-Optimization.patch
  aosp_diff/preliminary/art/0002-Coverity-Fixes.patch
  aosp_diff/preliminary/art/0003-Fixed-static-analysis-issue.patch
  aosp_diff/preliminary/frameworks/base/24_0024-Enable-ART-AutoFastJni.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2700 Port art avx2 patches to A15
  aosp_diff/preliminary/art/0004-Implement-AVX2-instructions-in-x64-assembler.patch
  aosp_diff/preliminary/art/0005-Introduce-the-notion-of-vector-registers.patch
  aosp_diff/preliminary/art/0006-Implement-AVX2-based-Vectorization-for-x86_64.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2697 ASB-NOV 2024 Security Patches integration
  aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/base_aaos/external/skia/0001-RESTRICT-AUTOMERGE-Avoid-potential-overflow-when-allocating-3D-.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0300--fix-Security-Report-Reveal-images-across-users-via-EditUserPh.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0301-Remove-authenticator-data-if-it-was-disabled-.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0302-Check-more-URIs-in-notifications.patch
  aosp_diff/base_aaos/frameworks/base/99_0303-Set-no-data-transfer-on-function-switch-timeout-for-accessory-mo.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0304-Disallow-device-admin-package-and-protected-packages.patch
  aosp_diff/base_aaos/frameworks/base/99_0305-RESTRICT-AUTOMERGE-Clear-app-provided-shortcut-icons.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Bluetooth/08_0008-Fix-permission-bypasses-to-multiple-methods.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Settings/43_0043-RESTRICT-AUTOMERGE-Stops-hiding-a11y-services-with-the-same-pack.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Settings/44_0044-startActivityForResult-with-new-Intent.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Settings/45_0045-Checks-cross-user-permission-before-handling-intent.bulletin.patch
  aosp_diff/base_aaos/packages/modules/Permission/08_0008-RESTRICT-AUTOMERGE-Fix-to-restrict-admin-from-granting-permissio.bulletin.patch
  aosp_diff/base_aaos/packages/modules/Wifi/0012-Fix-security-isseu-by-change-the-field-in-WifiConfig.bulletin.patch
  aosp_diff/base_aaos/packages/providers/MediaProvider/10_0010-Prevent-apps-from-renaming-files-they-don-t-own.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2694 ASB-NOV 2024 Security Patches integration
  aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/external/skia/0001-RESTRICT-AUTOMERGE-Avoid-potential-overflow-when-allocating-3D.patch
  aosp_diff/preliminary/frameworks/base/99_0285-fix-Security-Report-Reveal-images-across-users-via-EditUserPh.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0286-Remove-authenticator-data-if-it-was-disabled-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0288-Check-more-URIs-in-notifications.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0289-Set-no-data-transfer-on-function-switch-timeout-for-accessory-mo.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0290-Disallow-device-admin-package-and-protected-packages-to-be-reins.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0291-RESTRICT-AUTOMERGE-Clear-app-provided-shortcut-icons.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0292-Restrict-access-to-directories.bulletin.patch
  aosp_diff/preliminary/packages/apps/Bluetooth/05_0005-Fix-permission-bypasses-to-multiple-methods.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/43_0043-RESTRICT-AUTOMERGE-Stops-hiding-a11y-services-with-the-same-pack.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/44_0044-startActivityForResult-with-new-Intent.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/45_0045-RESTRICT-AUTOMERGE-Checks-cross-user-permission-before-handling-.bulletin.patch
  aosp_diff/preliminary/packages/modules/Permission/08_0008-RESTRICT-AUTOMERGE-Fix-to-restrict-admin-from-granting-permissio.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/0011-Fix-security-isseu-by-change-the-field-in-WifiConfig.bulletin.patch
  aosp_diff/preliminary/packages/providers/MediaProvider/10_0010-Prevent-apps-from-renaming-files-they-don-t-own.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2683 ASB-NOV 2024 Security Patches integration
  aosp_diff/preliminary/build/make/0009-Update-security_patch_level-string.patch
  aosp_diff/preliminary/external/skia/01_0001-RESTRICT-AUTOMERGE-Avoid-potential-overflow-when-allocating-3D-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/72_0072-Remove-authenticator-data-if-it-was-disabled-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/74_0074-Check-more-URIs-in-notifications.patch
  aosp_diff/preliminary/frameworks/base/75_0075-Set-no-data-transfer-on-function-switch-timeout-for-accessory-mo.bulletin.patch
  aosp_diff/preliminary/frameworks/base/76_0076-Disallow-device-admin-package-and-protected-packages-to-be-reins.bulletin.patch
  aosp_diff/preliminary/frameworks/base/77_0077-RESTRICT-AUTOMERGE-Clear-app-provided-shortcut-icons.patch
  aosp_diff/preliminary/frameworks/base/78_0078-Restrict-access-to-directories.bulletin.patch
  aosp_diff/preliminary/frameworks/native/05_0005-Fix-DisplayState-sanitization-.bulletin.patch
  aosp_diff/preliminary/frameworks/native/06_0006-Revert-Fix-DisplayState-sanitization-.bulletin.patch
  aosp_diff/preliminary/frameworks/native/07_0007-Fix-DisplayState-sanitization-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/18_0018-RESTRICT-AUTOMERGE-Stops-hiding-a11y-services-with-the-same-pack.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/19_0019-startActivityForResult-with-new-Intent.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/20_0020-Checks-cross-user-permission-before-handling-intent.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0012-Fix-permission-bypasses-to-multiple-methods.bulletin.patch
  aosp_diff/preliminary/packages/modules/Permission/0001-RESTRICT-AUTOMERGE-Fix-to-restrict-admin-from-granting-permissio.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/02_0002-Fix-security-isseu-by-change-the-field-in-WifiConfig.bulletin.patch
  aosp_diff/preliminary/packages/providers/MediaProvider/02_0002-Prevent-apps-from-renaming-files-they-don-t-own.bulletin.patch
  aosp_diff/preliminary/system/keymint/01_0001-Update-legacy-provisioning-msg-list.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful, Integration Approved

#2696 ASB-NOV 2024 Security Patches integration
  aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/base_aaos/external/skia/0001-RESTRICT-AUTOMERGE-Avoid-potential-overflow-when-allocating-3D-.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0295-fix-Security-Report-Reveal-images-across-users-via-EditUserPh.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0296-Remove-authenticator-data-if-it-was-disabled-.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0297-Check-more-URIs-in-notifications.patch
  aosp_diff/base_aaos/frameworks/base/99_0298-Set-no-data-transfer-on-function-switch-timeout-for-accessory-mo.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0299-Disallow-device-admin-package-and-protected-packages.patch
  aosp_diff/base_aaos/frameworks/base/99_0300-RESTRICT-AUTOMERGE-Clear-app-provided-shortcut-icons.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Bluetooth/07_0007-Fix-permission-bypasses-to-multiple-methods.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Settings/42_0043-RESTRICT-AUTOMERGE-Stops-hiding-a11y-services-with-the-same-pack.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Settings/44_0044-startActivityForResult-with-new-Intent.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Settings/45_0045-Checks-cross-user-permission-before-handling-intent.bulletin.patch
  aosp_diff/base_aaos/packages/modules/Permission/08_0008-RESTRICT-AUTOMERGE-Fix-to-restrict-admin-from-granting-permissio.bulletin.patch
  aosp_diff/base_aaos/packages/modules/Wifi/0012-Fix-security-isseu-by-change-the-field-in-WifiConfig.bulletin.patch
  aosp_diff/base_aaos/packages/providers/MediaProvider/10_0010-Prevent-apps-from-renaming-files-they-don-t-own.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2695 Asb v master nov 2024
  aosp_diff/preliminary/build/release/0001-Update-RELEASE_PLATFORM_SECURITY_PATCH-string.patch
  aosp_diff/preliminary/external/skia/0001-Avoid-potential-overflow-when-allocating-3D-mask-from-emboss-fil.bulletin.patch
  aosp_diff/preliminary/frameworks/base/0004-Remove-authenticator-data-if-it-was-disabled.patch
  aosp_diff/preliminary/frameworks/base/0005-Remove-visitPersonUri-flagged-code.patch
  aosp_diff/preliminary/frameworks/base/0006-Set-no-data-transfer-on-function-switch-timeout-for-.patch
  aosp_diff/preliminary/frameworks/base/0007-Disallow-device-admin-package-and-protected-packages.patch
  aosp_diff/preliminary/frameworks/base/0008-Restrict-access-to-directories.patch
  aosp_diff/preliminary/frameworks/native/04_0004-Fix-DisplayState-sanitization-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/02_0002-RESTRICT-AUTOMERGE-Stops-hiding-a11y-services-with-the-same-pack.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/03_0003-startActivityForResult-with-new-Intent.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/04_0004-Checks-cross-user-permission-before-handling-intent.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/0001-Fix-security-isseu-by-change-the-field-in-WifiConfig.bulletin.patch
  aosp_diff/preliminary/packages/providers/MediaProvider/0001-Prevent-apps-from-renaming-files-they-don-t-own.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2691 ASB-NOV 2024 Security Patches integration
  aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/external/skia/0002-RESTRICT-AUTOMERGE-Avoid-potential-overflow-when-allocating-3D-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0216-Remove-authenticator-data-if-it-was-disabled-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0217-SettingsProvider-verify-ringtone-URI-before-setting.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0219-Check-more-URIs-in-notifications.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0220-Set-no-data-transfer-on-function-switch-timeout-for-accessory-mo.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0221-Disallow-device-admin-package-and-protected-packages-to-be-reins.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0222-RESTRICT-AUTOMERGE-Clear-app-provided-shortcut-icons.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0223-Restrict-access-to-directories.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/0032-RESTRICT-AUTOMERGE-Stops-hiding-a11y-services-with-the-same-pack.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/0033-startActivityForResult-with-new-Intent.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/0034-Checks-cross-user-permission-before-handling-intent.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/59_0059-Fix-permission-bypasses-to-multiple-methods.patch
  aosp_diff/preliminary/packages/modules/Permission/0003-RESTRICT-AUTOMERGE-Fix-to-restrict-admin-from-granting-permissio.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/0016-Fix-security-isseu-by-change-the-field-in-WifiConfig.bulletin.patch
  aosp_diff/preliminary/packages/providers/MediaProvider/0008-Prevent-apps-from-renaming-files-they-don-t-own.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2699 ASB-NOV 2024 Security Patches integration
  aosp_diff/preliminary/build/make/0009-Update-security_patch_level-string.patch
  aosp_diff/preliminary/external/skia/01_0001-RESTRICT-AUTOMERGE-Avoid-potential-overflow-when-allocating-3D-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/73_0073-Remove-authenticator-data-if-it-was-disabled-.bulletin.patch
  aosp_diff/preliminary/frameworks/base/75_0075-Set-no-data-transfer-on-function-switch-timeout-for-accessory-mo.bulletin.patch
  aosp_diff/preliminary/frameworks/base/76_0076-Disallow-device-admin-package-and-protected-packages-to-be-reins.bulletin.patch
  aosp_diff/preliminary/frameworks/base/77_0077-RESTRICT-AUTOMERGE-Clear-app-provided-shortcut-icons.patch
  aosp_diff/preliminary/frameworks/base/78_0078-Restrict-access-to-directories.bulletin.patch
  aosp_diff/preliminary/frameworks/native/05_0005-Fix-DisplayState-sanitization-.bulletin.patch
  aosp_diff/preliminary/frameworks/native/06_0006-Revert-Fix-DisplayState-sanitization-.bulletin.patch
  aosp_diff/preliminary/frameworks/native/07_0007-Fix-DisplayState-sanitization-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/18_0018-RESTRICT-AUTOMERGE-Stops-hiding-a11y-services-with-the-same-pack.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/19_0019-startActivityForResult-with-new-Intent.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/20_0020-Checks-cross-user-permission-before-handling-intent.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0010-Fix-an-authentication-bypass-bug-in-SMP.bulletin.patch
  aosp_diff/preliminary/packages/modules/Bluetooth/0013-Fix-permission-bypasses-to-multiple-methods.bulletin.patch
  aosp_diff/preliminary/packages/modules/Permission/01_0001-RESTRICT-AUTOMERGE-Fix-to-restrict-admin-from-granting-permissio.bulletin.patch
  aosp_diff/preliminary/packages/modules/Wifi/02_0002-Fix-security-isseu-by-change-the-field-in-WifiConfig.bulletin.patch
  aosp_diff/preliminary/packages/providers/MediaProvider/02_0002-Prevent-apps-from-renaming-files-they-don-t-own.bulletin.patch
  aosp_diff/preliminary/system/keymint/01_0001-Update-legacy-provisioning-msg-list.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2705 ExternalCameraHAL: Fix incorrect nullptr check on bufPtr
  aosp_diff/caas/hardware/interfaces/0001-ExternalCameraHAL-Fix-incorrect-nullptr-check-on-buf.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2711 Fix JavaCrash of android.car.usb.handler
  aosp_diff/aaos_iasw/packages/services/Car/0003-Fix-JavaCrash-of-android.car.usb.handler.patch
Labels: Invalid commit message, PR approved, Developer Approved, Engineering Build Successful

#2722 Add run time permissions for CarDialer application
  aosp_diff/base_aaos/packages/apps/Car/DialerPrebuilt/0001-Add-run-time-permissions-for-CarDialer-application.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2721 Fix CursorIndexOutOfBoundsException on com.android.gallery3d
  aosp_diff/aaos_iasw/packages/apps/Gallery2/0003-Fix-CursorIndexOutOfBoundsException-on-com.android.g.patch
Labels: Invalid commit message, PR approved, Developer Approved, Engineering Build Successful

#2724 Update config for v6.6.56 rebase
  host/kernel/lts2023-chromium/x86_64_defconfig
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2726 Fix metadata issue when reconnect pixel
  aosp_diff/base_aaos/packages/modules/Bluetooth/0001-Fix-metadata-issue-when-reconnect-pixel.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2727 Fix for improper text alignment in bluetooth rename dialogbox
  aosp_diff/base_aaos/packages/apps/Car/Settings/0001-Fix-for-improper-text-alignment-in-bluetooth-rename-.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2734 Fix error on joystick operation
  aosp_diff/aaos_iasw/frameworks/native/0002-Fix-error-on-joystick-operation.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2735 bsp_diff patch cleanup
  bsp_diff/common/vendor/intel/hardware/interfaces/0003-Upgrade-thermal-HAL-AIDL-version-from-1-to-2.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2737 Apply WindowInsets for MainCameraActivity
  aosp_diff/preliminary/packages/apps/Camera2/05_0005-Apply-Window-Insets-for-MainCameraActivity.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful
