Repository projectceladon/vendor-intel-utils, pull requests merged in 2024-09, with the labels that each got.

#2576 ASB-SEP 2024 Security Patches integration
  aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/base_aaos/frameworks/av/43_0043-omx-check-HDR10-info-param-size.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0293-DO-NOT-MERGE-Ignore-Sanitized-uri-scheme-by-removing.patch
  aosp_diff/base_aaos/frameworks/base/99_0294-RESTRICT-AUTOMERGE-Delete-keystore-keys-from-Recover.patch
  aosp_diff/base_aaos/packages/apps/Settings/38_0038-Limit-wifi-item-edit-content-s-max-length-to-500.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Settings/39_0039-Replace-getCallingActivity-with-getLaunchedFromPackage-.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Settings/40_0040-Ignore-fragment-attr-from-ext-authenticator-resource.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Settings/41_0041-RESTRICT-AUTOMERGE-Restrict-Settings-Homepage-prior-to-provision.bulletin.patch
  aosp_diff/base_aaos/packages/services/Telecomm/15_0015-Unbind-CallScreeningService-when-timeout-reached-.bulletin.patch
  aosp_diff/base_aaos/system/sepolicy/13_0013-RESTRICT-AUTOMERGE-Allow-system_server-to-call-IKeystoreMaintena.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2574 ASB-SEP 2024 Security Patches integration
  aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/av/0033-omx-check-HDR10-info-param-size.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0209-DO-NOT-MERGE-Ignore-Sanitized-uri-scheme-by-removing.patch
  aosp_diff/preliminary/frameworks/base/99_0210-RESTRICT-AUTOMERGE-Delete-keystore-keys-from-RecoveryService-reb.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/0027-Replace-getCallingActivity-with-getLaunchedFromPackage-.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/0028-Limit-wifi-item-edit-content-s-max-length-to-500.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/0029-Ignore-fragment-attr-from-ext-authenticator-resource.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/0030-RESTRICT-AUTOMERGE-Restrict-Settings-Homepage-prior-to-provision.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/0013-Unbind-CallScreeningService-when-timeout-reached-.bulletin.patch
  aosp_diff/preliminary/system/sepolicy/12_0012-Allow-system_server-to-call-IKeystoreMaintenance-deleteAllKeys-.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2581 ASB-SEP 2024 Security Patches integration
  aosp_diff/preliminary/build/make/0009-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/av/0009-omx-check-HDR10-info-param-size.bulletin.patch
  aosp_diff/preliminary/frameworks/base/67_0067-DO-NOT-MERGE-Ignore-Sanitized-uri-scheme-by-removing.patch
  aosp_diff/preliminary/frameworks/base/68_0068-Delete-keystore-keys-from-RecoveryService-rebootRecoveryWithComm.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/14_0014-Limit-wifi-item-edit-content-s-max-length-to-500.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/15_0015-Ignore-fragment-attr-from-ext-authenticator-resource.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/16_0016-RESTRICT-AUTOMERGE-Restrict-Settings-Homepage-prior-to-provision.bulletin.patch
  aosp_diff/preliminary/packages/modules/RemoteKeyProvisioning/01_0001-RESTRICT-AUTOMERGE-Allow-System-user-to-call-getRegistration-AP.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/01_0001-Unbind-CallScreeningService-when-timeout-reached-.bulletin.patch
  aosp_diff/preliminary/system/sepolicy/13_0013-Allow-system_server-to-call-IKeystoreMaintenance-deleteAllKeys-.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2586 revert patch of "Disable VP9 HDR support by default"
  aosp_diff/preliminary/frameworks/av/0009-By-default-disable-HDR-support-for-VP9-codec.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2580 ASB-SEP 2024 Security Patches integration.
  aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/base_aaos/frameworks/av/42_0042-omx-check-HDR10-info-param-size.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0289-DO-NOT-MERGE-Ignore-Sanitized-uri-scheme-by-removing.patch
  aosp_diff/base_aaos/frameworks/base/99_0290-RESTRICT-AUTOMERGE-Delete-keystore-keys-from-Recover.patch
  aosp_diff/base_aaos/packages/apps/Settings/38_0038-Limit-wifi-item-edit-content-s-max-length-to-500.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Settings/39_0039-Replace-getCallingActivity-with-getLaunchedFromPackage-.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Settings/40_0040-Ignore-fragment-attr-from-ext-authenticator-resource.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Settings/41_0041-RESTRICT-AUTOMERGE-Restrict-Settings-Homepage-prior-to-provision.bulletin.patch
  aosp_diff/base_aaos/packages/services/Telecomm/15_0015-Unbind-CallScreeningService-when-timeout-reached-.bulletin.patch
  aosp_diff/base_aaos/system/sepolicy/13_0013-RESTRICT-AUTOMERGE-Allow-system_server-to-call-IKeystoreMaintena.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2577 ASB-Sep 2024 Security Patches integration
  aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/av/40_0040-omx-check-HDR10-info-param-size.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0279-DO-NOT-MERGE-Ignore-Sanitized-uri-scheme-by-removing-scheme-de.bulletin.patch
  aosp_diff/preliminary/frameworks/base/99_0280-RESTRICT-AUTOMERGE-Delete-keystore-keys-from-RecoveryService-reb.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/38_0038-Limit-wifi-item-edit-content-s-max-length-to-500.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/39_0039--RESTRICT-AUTOMERGE-Replace-getCallingActivity-with-getLaunch.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/40_0040-Ignore-fragment-attr-from-ext-authenticator-resource.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/41_0041-RESTRICT-AUTOMERGE-Restrict-Settings-Homepage-prior-to-provision.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/15_0015-Unbind-CallScreeningService-when-timeout-reached-.bulletin.patch
  aosp_diff/preliminary/system/sepolicy/12_0012-RESTRICT-AUTOMERGE-Allow-system_server-to-call-IKeystoreMaintena.bulletin.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2594 Fix for coverity issue for memtrack_module
  aosp_diff/preliminary/hardware/interfaces/15_0015-Fix-for-coverity-issue-for-memtrack_module.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2595 Fix for coverity issue for memtrack_module
  aosp_diff/preliminary/hardware/interfaces/15_0015-Fix-for-coverity-issue-for-memtrack_module.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful, Integration Approved

#2603 Remove nnhal and its dependent component diff patches
  bsp_diff/common/vendor/intel/external/project-celadon/ade/01_0001-Add-Android.bp-for-ade.patch
  bsp_diff/common/vendor/intel/external/project-celadon/nn-hal/0001-WA-Disabled-operations-causing-VTS-failures.patch
  bsp_diff/common/vendor/intel/external/project-celadon/nn-hal/0002-Add-libtflite_static-to-address-undefined-symbol-bui.patch
  bsp_diff/common/vendor/intel/external/project-celadon/oneDNN/0001-Changes-to-add-oneDNN-for-OpenVINO-2022.3.0.patch
  bsp_diff/common/vendor/intel/external/project-celadon/oneTBB/0001-Changes-to-compile-oneTBB-for-Android.patch
  bsp_diff/common/vendor/intel/external/project-celadon/openvino/0001-Changes-to-integrate-openvino-2022.3.0.patch
  bsp_diff/common/vendor/intel/external/project-celadon/pugixml/0001-Changes-to-integrate-openvino-2022.3.0.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2602 Move the graphics a15 patches to respective git projects
  bsp_diff/common/device/intel/mixins/0005-Fixed-graphics-allocator-hal-issue.patch
  bsp_diff/common/device/intel/mixins/0012-Remove-graphics-mapper4.patch
  bsp_diff/common/device/intel/mixins/0022-Update-composer-aidl-version-to-3.patch
  bsp_diff/common/device/intel/mixins/0030-Fix-for-flickering-issue.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2598 Removing few WA patches
  aosp_diff/preliminary/build/make/0004-Remove-usage-of-F-string.patch
  aosp_diff/preliminary/build/make/0005-WA-Revert-Handle-symlinks-when-extracting-zipfiles.patch
  aosp_diff/preliminary/build/make/0006-WA-Revert-Handle-zip64-extra-fields-better.patch
  aosp_diff/preliminary/build/make/0007-WA-Revert-Fix-python3.11-s-support-for-zip64.patch
  aosp_diff/preliminary/build/make/0008-WA-Revert-Use-python-based-unzip-function-for-portabili.patch
  aosp_diff/preliminary/build/tools/01_0001-Remove-usage-of-F-string.patch
  aosp_diff/preliminary/build/tools/03_0003-WA-Fixed-Build-Error-Releasetools.patch
  aosp_diff/preliminary/prebuilts/build-tools/01_0001-WA-Fixed-Build-Error-For-Python.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful, Integration Approved

#2604 libwifihal: Move the change to respective git project
  bsp_diff/common/hardware/intel/wlan/libwifihal/open/0001-Changes-to-compile-libwifihal-with-latest-Android.patch
Labels: Valid commit message, PR approved, Pending Developer Approval, Engineering Build Successful

#2597 ASB-SEP 2024 Security Patches integration
  aosp_diff/preliminary/build/make/0009-Update-security_patch_level-string.patch
  aosp_diff/preliminary/frameworks/av/0009-omx-check-HDR10-info-param-size.bulletin.patch
  aosp_diff/preliminary/frameworks/base/67_0067-DO-NOT-MERGE-Ignore-Sanitized-uri-scheme-by-removing.patch
  aosp_diff/preliminary/frameworks/base/68_0068-Delete-keystore-keys-from-RecoveryService-rebootRecoveryWithComm.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/14_0014-Limit-wifi-item-edit-content-s-max-length-to-500.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/15_0015-Ignore-fragment-attr-from-ext-authenticator-resource.bulletin.patch
  aosp_diff/preliminary/packages/apps/Settings/16_0016-RESTRICT-AUTOMERGE-Restrict-Settings-Homepage-prior-to-provision.bulletin.patch
  aosp_diff/preliminary/packages/modules/RemoteKeyProvisioning/01_0001-RESTRICT-AUTOMERGE-Allow-System-user-to-call-getRegistration-AP.bulletin.patch
  aosp_diff/preliminary/packages/services/Telecomm/01_0001-Unbind-CallScreeningService-when-timeout-reached-.bulletin.patch
  aosp_diff/preliminary/system/sepolicy/13_0013-Allow-system_server-to-call-IKeystoreMaintenance-deleteAllKeys-.bulletin.patch
Labels: Invalid commit message, Valid commit message, PR approved, Developer Approved, Engineering Build Successful, Integration Approved

#2599 Fix error when playback can't be resumed on LocalMediaPlayer
  aosp_diff/aaos_iasw/packages/apps/Car/LocalMediaPlayer/0001-Fix-error-when-playback-can-t-be-resumed-on-LocalMed.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2590 Removing few WA patches
  aosp_diff/preliminary/build/make/0004-Remove-usage-of-F-string.patch
  aosp_diff/preliminary/build/make/0005-WA-Revert-Handle-symlinks-when-extracting-zipfiles.patch
  aosp_diff/preliminary/build/make/0006-WA-Revert-Handle-zip64-extra-fields-better.patch
  aosp_diff/preliminary/build/make/0007-WA-Revert-Fix-python3.11-s-support-for-zip64.patch
  aosp_diff/preliminary/build/make/0008-WA-Revert-Use-python-based-unzip-function-for-portabili.patch
  aosp_diff/preliminary/build/tools/01_0001-Remove-usage-of-F-string.patch
  aosp_diff/preliminary/build/tools/03_0003-WA-Fixed-Build-Error-Releasetools.patch
  aosp_diff/preliminary/prebuilts/build-tools/01_0001-WA-Fixed-Build-Error-For-Python.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2600 Coverity fixes for thermal-daemon
  aosp_diff/base_aaos/external/thermal_daemon/0001-Coverity-fixes-for-Thermal-Daemon.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2608 Revert "[REVERT ME] Disable out of kernel tree i915 module build"
  bsp_diff/aaos_iasw/device/intel/project-celadon/aaos_iasw/0001-REVERT-ME-Disable-out-of-kernel-tree-i915-module-bui.patch
  bsp_diff/base_aaos/device/intel/project-celadon/base_aaos/0004-REVERT-ME-Disable-out-of-kernel-tree-i915-module-bui.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2614 Enable Displaying lunch menu for A15
  vendorsetup.sh
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2609 Fix static analysis issues for thermal daemon for IVI
  aosp_diff/base_aaos/external/thermal_daemon/0002-Fix-static-analysis-issues-for-thermal-daemon-for-IV.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2615 CI builder TARGET_RELEASE agnostic lunch support
  vendorsetup.sh
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2605 git Ga910
  aosp_diff/aaos_iasw/packages/apps/Gallery2/0001-Fixed-for-Crashes-in-Gallery-App.patch
Labels: Invalid commit message, PR approved, Developer Approved, Engineering Build Successful

#2593 Remove few WA patches
  aosp_diff/base_aaos/build/make/0002-WA-Replaced-python-files-from-A14.patch
  aosp_diff/base_aaos/prebuilts/build-tools/01_0001-WA-Fixed-Build-Error-For-Python.patch
  bsp_diff/base_aaos/device/intel/build/0002-Fixed-build-error-due-to-python3.patch
  bsp_diff/caas/device/intel/build/0001-Migrate-python2-scripts-to-python3.patch
  bsp_diff/caas/device/intel/common/0001-Migrate-gpt_ini2bin.py-to-python3.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2621 fix for OTA update through script failure
  bsp_diff/common/device/intel/sepolicy/0002-fix-for-OTA-update-through-script-failure.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful, Integration Approved

#2620 fix for OTA update through script failure
  bsp_diff/common/device/intel/sepolicy/0002-fix-for-OTA-update-through-script-failure.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2624 Fix for default notification sound.
  aosp_diff/preliminary/frameworks/base/69_0069-Fix-for-default-notification-sound.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2616 Post power state listener broadcast calls to handler
  aosp_diff/aaos_iasw/packages/services/Car/0002-Post-power-state-listener-broadcast-calls-to-handler.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2623 Update i915 sysfs memtrack patch
  bsp_diff/common/kernel/lts2022-chromium/0007-drm-i915-Sysfs-interface-to-get-GFX-shmem-usage.patch
Labels: Valid commit message, PR approved, Developer Approved, Integration Approved

#2626 Fixed for Deadlock in IMMS Proxy Service
  aosp_diff/preliminary/frameworks/opt/car/services/0001-Fixed-for-Deadlock-in-IMMS-Proxy-Service.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2628 dkms: optimize the dg2 kernel driver loading time
  bsp_diff/common/vendor/linux/firmware/0002-dkms-add-dg2-kernel-modules-as-binary.patch
Labels: Valid commit message, PR approved, Pending Developer Approval, Engineering Build Successful

#2631 Removal of unused 5.15 kernel
  bsp_diff/common/kernel/linux-intel-lts2021/0001-make-vmmouse-report-relative-values.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0002-greybus-Remove-Android.mk.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0003-Bluetooth-SCO-USB-driver.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0004-uvc-Add-UVC-GET_DEF-probe-quirk-for-C922-camera.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0005-btusb-snd-crash-while-disconnect.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0006-Bluetooth-btusb-Add-reset-on-close-quirk-for-Intel-a.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0007-9p-freezing-aborts-when-use-wait_event_killable.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0008-iwlwifi-Vendor-command-support-in-iwlwifi-driver.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0009-x86-relocs-Ignore-L4_PAGE_OFFSET-relocations.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0010-replace-cond_resched-with-usleep_range-to-avoid-dead.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0011-Use-clang-toolchain-from-prebuilts-instead-of-gcc.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0012-Fix-for-btusb_sco_snd_card-not-getting-probed.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0013-Add-support-for-AX211-GarfieldPeak-Gfp.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0014-ACPI-PM-Propagate-power-button-event-to-user-space-w.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0015-VIRTIO-Freeze-and-Restore-Implementation.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0016-Skip-hw-pmu-for-VM-on-ADL.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0017-Bluetooth-btusb-Add-reset-on-close-quirk-for-Intel-a.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0018-Fix-build-error-in-few-setups-due-to-change-introduc.patch
  bsp_diff/common/kernel/linux-intel-lts2021/0019-updating-dummy-cpufreq_frequency_table.patch
  bsp_diff/common/kernel/lts2021-chromium/0001-make-vmmouse-report-relative-values.patch
  bsp_diff/common/kernel/lts2021-chromium/0002-greybus-Remove-Android.mk.patch
  bsp_diff/common/kernel/lts2021-chromium/0003-Bluetooth-SCO-USB-driver.patch
  bsp_diff/common/kernel/lts2021-chromium/0004-uvc-Add-UVC-GET_DEF-probe-quirk-for-C922-camera.patch
  bsp_diff/common/kernel/lts2021-chromium/0005-btusb-snd-crash-while-disconnect.patch
  bsp_diff/common/kernel/lts2021-chromium/0006-Bluetooth-btusb-Add-reset-on-close-quirk-for-Intel-a.patch
  bsp_diff/common/kernel/lts2021-chromium/0007-9p-freezing-aborts-when-use-wait_event_killable.patch
  bsp_diff/common/kernel/lts2021-chromium/0008-iwlwifi-Vendor-command-support-in-iwlwifi-driver.patch
  bsp_diff/common/kernel/lts2021-chromium/0009-x86-relocs-Ignore-L4_PAGE_OFFSET-relocations.patch
  bsp_diff/common/kernel/lts2021-chromium/0010-drm-i915-replace-cond_resched-with-usleep_range-to-a.patch
  bsp_diff/common/kernel/lts2021-chromium/0011-Prebuilts-tar-doesnot-support-I-option.-So-replaced-.patch
  bsp_diff/common/kernel/lts2021-chromium/0012-Fix-for-btusb_sco_snd_card-not-getting-probed.patch
  bsp_diff/common/kernel/lts2021-chromium/0014-drm-i915-Sysfs-interface-to-get-GFX-shmem-usage.patch
  bsp_diff/common/kernel/lts2021-chromium/0016-iwl7000-Add-driver-and-firmware-version-query-suppor.patch
  bsp_diff/common/kernel/lts2021-chromium/0017-Add-HFP-support-for-AX211-GarfieldPeak-Gfp.patch
  bsp_diff/common/kernel/lts2021-chromium/0018-ACPI-PM-Propagate-power-button-event-to-user-space-w.patch
  bsp_diff/common/kernel/lts2021-chromium/0019-Freeze-and-Restore-Implementation.patch
  bsp_diff/common/kernel/lts2021-chromium/0020-Skip-hw-pmu-for-VM-on-ADL.patch
  bsp_diff/common/kernel/lts2021-chromium/0021-fix-for-coverity-issues.patch
  bsp_diff/common/kernel/lts2021-chromium/0022-Fix-build-issue-in-wifi-driver.patch
  bsp_diff/common/kernel/lts2021-chromium/0023-updating-dummy-cpufreq_frequency_table.patch
  host/kernel/linux-intel-lts2021/README
  host/kernel/linux-intel-lts2021/build.sh
  host/kernel/linux-intel-lts2021/build_weekly.sh
  host/kernel/linux-intel-lts2021/x86_64_defconfig
  host/kernel/lts2021-chromium/0001-Revert-FROMLIST-KVM-mmu-remove-over-aggressive-warni.patch
  host/kernel/lts2021-chromium/0002-Revert-FROMLIST-KVM-arm64-mmu-use-gfn_to_pfn_page.patch
  host/kernel/lts2021-chromium/0003-Revert-FROMLIST-KVM-x86-mmu-use-gfn_to_pfn_page.patch
  host/kernel/lts2021-chromium/0004-Revert-FROMLIST-KVM-mmu-introduce-new-gfn_to_pfn_pag.patch
  host/kernel/lts2021-chromium/0005-Fix-device-hang-on-TGL-RVP.patch
  host/kernel/lts2021-chromium/README
  host/kernel/lts2021-chromium/build.sh
  host/kernel/lts2021-chromium/build_weekly.sh
  host/kernel/lts2021-chromium/x86_64_defconfig
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2613 Cleanup bsp_diff changes.
  bsp_diff/aaos_iasw/device/intel/mixins/0001-adding-required-sensors-xml-files-for-automotive.patch
  bsp_diff/base_aaos/device/intel/mixins/0001-adding-required-sensors-xml-files-for-automotive.patch
  bsp_diff/base_aaos/device/intel/mixins/0002-adding-required-uncalibrated-sensors-xml-files-for-a.patch
Labels: Valid commit message, PR approved, Pending Developer Approval, Engineering Build Successful

#2635 Remove the device-intel-build common patches
  bsp_diff/common/device/intel/build/0001-Updated-clang-version-for-Android-15.patch
  bsp_diff/common/device/intel/build/0002-WA-Fix-for-FILE_NAME_TAG.patch
  bsp_diff/common/device/intel/build/0004-Updated-compressing-binary-in-A15.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2630 Add test kernel module for system and odm DLKM partition
  bsp_diff/base_aaos/device/intel/mixins/0003-Add-test-kernel-module-for-system-and-odm-DLKM-parti.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2640 Cleanup of common mixins folder
  bsp_diff/common/device/intel/mixins/0002-TARGET_USES_64_BIT_BINDER-has-been-deprecated.patch
  bsp_diff/common/device/intel/mixins/0003-Replace-FILE_NAME_TAG-with-intel.patch
  bsp_diff/common/device/intel/mixins/0006-Disabled-wi-fi-display-service.patch
  bsp_diff/common/device/intel/mixins/0008-Add-APEX-version-of-thermal-AIDL-in-product-packages.patch
  bsp_diff/common/device/intel/mixins/0009-Updated-media-c2-hal-from-hidl-to-aidl.patch
  bsp_diff/common/device/intel/mixins/0010-W-A-Disable-trusty-for-BM-boot.patch
  bsp_diff/common/device/intel/mixins/0011-Add-BT-HAL-aidl-service-in-product-packages.patch
  bsp_diff/common/device/intel/mixins/0013-camera-use-default-vendor-hal.patch
  bsp_diff/common/device/intel/mixins/0014-WA-Disabling-settingthe-vndk-and-sepolicy-version.patch
  bsp_diff/common/device/intel/mixins/0015-WA-Disable-gatekeeper-aidl-for-A15-BM-boot.patch
  bsp_diff/common/device/intel/mixins/0016-Removing-deprecated-HALs-from-A15.patch
  bsp_diff/common/device/intel/mixins/0017-Remove-32bit-support-in-AOSP14.patch
  bsp_diff/common/device/intel/mixins/0018-Removed-deprecated-HAL-renderscript.patch
  bsp_diff/common/device/intel/mixins/0020-Updated-media-c2-hal-from-hidl-to-aidl.patch
  bsp_diff/common/device/intel/mixins/0023-Migrate-HIDL-Software-Gatekeeper-to-AIDL.patch
  bsp_diff/common/device/intel/mixins/0024-Update-the-API-and-target-level-for-A15.patch
  bsp_diff/common/device/intel/mixins/0025-Enabling-Software-Gatekeeper-to-AIDL.patch
  bsp_diff/common/device/intel/mixins/0026-Remove-omx-interface.patch
  bsp_diff/common/device/intel/mixins/0027-Updating-the-sepolicy-version-and-sdk-version.patch
  bsp_diff/common/device/intel/mixins/0028-Code-cleanup.patch
  bsp_diff/common/device/intel/mixins/0032-W-A-linux-intel-lts2023-Disable-trusty-for-BM-boot.patch
  bsp_diff/common/device/intel/mixins/0033-Enable-AIDL-for-audio.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#2644 Fix method not found for NotProvisionedException hidden api
  aosp_diff/base_aaos/frameworks/base/100_Fix-method-not-found-for-NotProvisionedException-hidden-api.patch
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful
