Repository projectceladon/vendor-intel-utils, pull requests merged in 2024-01, with the labels that each got.

#2280 Fixed issue in base_aaos patch application
  autopatch.sh
Labels: Valid commit message, PR approved

#2281 Fixed to support playing .mkv & .ts videos from File App.
  aosp_diff/base_aaos/packages/apps/Gallery2/0006-Fixed-to-support-playing-mkv-ts-videos-from-File-A.patch
Labels: Valid commit message, PR approved

#2283 Removed Telephony module in IVI.
  aosp_diff/base_aaos/build/make/0006-Removed-Telephony-module-in-IVI.patch
  aosp_diff/base_aaos/frameworks/base/99_0234-Removed-Telephony-module-in-IVI.patch
Labels: Valid commit message, PR approved

#2273 ASB - January 2024 Security Patches integration
  aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch
  aosp_diff/base_aaos/frameworks/av/34_0034-Codec2BufferUtils-Use-cropped-dimensions-in-RGB-to-YUV-conversi.bulletin.patch
  aosp_diff/base_aaos/frameworks/av/35_0035-Fix-convertYUV420Planar16ToY410-overflow-issue-for-unsupported-c.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0234-Add-placeholder-when-media-control-title-is-blank.patch
  aosp_diff/base_aaos/frameworks/base/99_0235-Revert-Dismiss-keyguard-when-simpin-auth-d-and-.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0236--SB-Privacy-Fetch-current-active-appops-on-startup-.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0237-Fix-vulnerability-that-allowed-attackers-to-start-arbitary-activ.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0238-DO-NOT-MERGE-Fix-ActivityManager-killBackgroundProcesses-permis.bulletin.patch
  aosp_diff/base_aaos/frameworks/base/99_0239-DO-NOT-MERGE-Ensure-finish-lockscreen-when-usersetup-incomplete.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Camera2/05_0005-Camera2-Do-not-pass-location-info-for-startActivity-case.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Car/Settings/04_0004-CVE_2022_20234-test-failed-due-to-notification-acces.patch
  aosp_diff/base_aaos/packages/apps/Nfc/0002-Possible-deadlock-on-the-NfcService-object.bulletin.patch
  aosp_diff/base_aaos/packages/apps/Settings/37_0037-Validate-ringtone-URIs-before-setting.bulletin.patch
  aosp_diff/base_aaos/packages/modules/NeuralNetworks/0007-Fix-OOB-Read-in-convertSubgraphFromHAL.bulletin.patch
  aosp_diff/base_aaos/system/bt/49_0049--conflict-Merge-Fix-some-OOB-errors-in-BTM-parsing-into-rvc-d.bulletin.patch
Labels: Valid commit message, PR approved

#2285 Fixed for Toast message size view.
  aosp_diff/base_aaos/packages/apps/Car/Settings/0005-Fixed-for-Toast-message-size-view.patch
Labels: Valid commit message, PR approved

#2251 ignore whitespace changes
  autopatch.sh
Labels: Valid commit message, PR approved

#2292 Fixed for Crash in com.android.phone in IVI
  aosp_diff/base_aaos/build/make/0006-Removed-Telephony-module-in-IVI.patch
  aosp_diff/base_aaos/frameworks/base/99_0234-Removed-Telephony-module-in-IVI.patch
  aosp_diff/base_aaos/frameworks/base/99_0240-Fixed-for-Crash-in-com.android.phone-during-Stabilit.patch
Labels: Valid commit message, PR approved

#2278 [WA] Add AppOverrideSettings to hack app layout behavious
  aosp_diff/base_aaos/frameworks/base/0001-Add-AppOverrideSettings-to-hack-app-layout-behavious.patch
Labels: Invalid commit message

#2295 Add deviceIds checking back
  aosp_diff/base_aaos/frameworks/av/26_0026-Camera-fix-uvc-cameraid-mNumberOfCameras-issue.patch
  aosp_diff/base_aaos/frameworks/av/27_0027-Revoke-deviceIds-checking.patch
Labels: Valid commit message, PR approved

#2293 Fixed for boot to recovery mode after G3 boot and Cold boot.
  aosp_diff/base_aaos/frameworks/base/99_0241-Make-caller-wait-for-installd-to-become-available.patch
Labels: Valid commit message, PR approved, Developer Approved

#2294 move patch from preliminary/ to base_aaos
  aosp_diff/base_aaos/frameworks/base/99_0241-add-flag-to-skip-removing-permissions-in-clearApplic.patch
Labels: Valid commit message, PR approved, Developer Approved

#2301 Fixed for crashe during Monkey test run.
  aosp_diff/base_aaos/frameworks/base/99_0242-Fixed-for-crashe-during-Monkey-test-run.patch
Labels: Valid commit message, PR approved

#2303 Add deviceIds checking back
  aosp_diff/base_aaos/frameworks/av/26_0026-Camera-fix-uvc-cameraid-mNumberOfCameras-issue.patch
  aosp_diff/base_aaos/frameworks/av/27_0027-Revoke-deviceIds-checking.patch
Labels: Valid commit message, PR approved

#2322 Create run_ci_checks.yaml
  .github/workflows/run_ci_checks.yaml
Labels: Invalid commit message

#2323 Update and rename Runchecks.yaml to run_ci_checks.yaml
  .github/workflows/Runchecks.yaml
  .github/workflows/run_ci_checks.yaml
Labels: Invalid commit message

#2302 Fix null pointer dereference coverity
  aosp_diff/base_aaos/packages/apps/Car/Settings/05_0005-Fix-null-pointer-dereference-coverity.patch
Labels: Valid commit message, PR approved, Developer Approved

#2321 Remove bsp diff patches for sepolicy
  bsp_diff/base_aaos/device/intel/sepolicy/0001-Adding-car-UI-lunch-target.patch
Labels: Valid commit message, PR approved

#2324 Revert "Remove uuid when device leaves bonded state"
  aosp_diff/base_aaos/packages/apps/Bluetooth/06_0006-Revert-Remove-uuid-when-device-leaves-bonded-state.patch
Labels: Invalid commit message
